### ISSUE TITLE
ToArrayAsync / CountAsync Blocking forever if using inline vars in LINQ code

### ISSUE THREAD

**Issue by xumix** [dotnet/efcore#10315]
This query never gets executed:
```
var query = db.Entities;
            var res= await (
                from s in query 
                let b = s.Ones.FirstOrDefault()
                let u = s.Others.FirstOrDefault(f => f.TypeId == 1)
                select new TenderDto
                {
                    Id = s.Id,
                    One= b.One!= null && b.One.Other != null ? b.One.Other.Name : null,
                    One = u != null && u.Other != null ? u.Other.Other2 : null,
                }).ToArrayAsync();
var count =  await db.Entities.CountAsync()

```
Entities - just a normal entity, Ones &Other - some collections declared as virtual
Count never gets executed

If I change to
```
var query = db.Entities;
            var res= (
                from s in query 
                let b = s.Ones.FirstOrDefault()
                let u = s.Others.FirstOrDefault(f => f.TypeId == 1)
                select new TenderDto
                {
                    Id = s.Id,
                    One= b.One!= null && b.One.Other != null ? b.One.Other.Name : null,
                    One = u != null && u.Other != null ? u.Other.Other2 : null,
                }).ToArray();
var count =  db.Entities.Count()
```
then the query works OK. If I remove inline b and u declaration, it also works with async

### Further technical details
EF Core version: 2.0.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: windows 10
IDE: Visual Studio 2017

**Comment by vladislav-karamfilov** [comment]
This is fixed in 2.0.1.

**Comment by xumix** [comment]
@vladislav-karamfilov THX

**Comment by ajcvickers** [comment]
@xumix Have you tried with 2.0.1 and confirmed that it is not fixed? If so, can you post a complete project or code listing that reproduces what you are seeing?
