### ISSUE TITLE
Nested projections with null check or access to parent navigation property => exception

### ISSUE THREAD

**Issue by joakimriedel** [dotnet/efcore#13220]
Using nested projections with null checks or trying to access a parent navigation property in a child projection, all throws exceptions.

### Steps to reproduce

I have a project with these two entities below;

```c#
public class Offer
    {
        public int Id { get; set; }
        public ICollection<OfferAction> Actions { get; set; }
    }

public enum OfferActions : int
    {
        Established = 1
    }

public class OfferAction
    {
        public int Id { get; set; }

        [Required]
        public Offer Offer { get; set; }
        public int OfferId { get; set; }

        [Required]
        public DateTime TimeCreatedUtc { get; set; }

        [Required]
        public OfferActions Action { get; set; }
    }
```

I'm having an AutoMapper configuration where child entities are accessing the parent entity through a navigation property.

```c#
// AutoMapper map
CreateMap<Offer, OfferDto>()
.ForMember(m => m.LastAction, opt => opt.MapFrom(m => m.Actions.OrderByDescending(a => a.TimeCreatedUtc).FirstOrDefault()));

CreateMap<OfferAction, OfferActionDto>()
.ForMember(m => m.AnyEstablished, opt => opt.MapFrom(m => m.Offer.Actions.Any(a => a.Action == OfferActions.Established)));

await _context.Offers
.ProjectTo<OfferDto>()
.ToListAsync()
```

AutoMapper generates code that translates to the following EF Core query.

```c#
                var query1 = context.Ads.Select(dtoAd => new AdDto()
                {
                    Offers = dtoAd.Offers.Select(dtoOffer => new
                    {
                        __LastAction = dtoOffer.Actions.OrderByDescending(a => a.TimeCreatedUtc).FirstOrDefault(),
                        Id = dtoOffer.Id
                    })
                    .Select(dtoLet => new OfferDto()
                    {
                        Id = dtoLet.Id,
                        LastAction = dtoLet.__LastAction == null ? null : new OfferActionDto()
                        {
                            Action = dtoLet.__LastAction.Action,
                            TimeCreatedUtc = dtoLet.__LastAction.TimeCreatedUtc,
                            AnyEstablished = dtoLet.__LastAction.Offer.Actions.Any(a => a.Action == OfferActions.Established)
                        }
                    })
                    .ToList()
                });
```

Running this query renders the following exceptions, depending on provider and on whether QueryClientEvaluationWarning is configured or not.

```c#
// INMEMORY: System.ArgumentNullException: 'Value cannot be null.'
// SQL (without QueryClientEvaluationWarning): System.InvalidOperationException: 'No mapping to a relational type can be found for the CLR type 'object'.'
// SQL (with QueryClientEvaluationWarning): System.InvalidOperationException: 'Error generated for warning 'Microsoft.EntityFrameworkCore.Query.QueryClientEvaluationWarning: The LINQ expression 'where (Convert([a].Action, Int32) == 1)' could not be translated and will be evaluated locally.'. 
```

If I remove the nesting one level, and project the "Offers" collection directly instead, I get another variation of errors. Note that if the offending line marked with the comment below is removed, the null check of *__LastAction* will work properly - which does not work in *query1* where the null check is nested in another projection.

```c#
                var query2 = context.Offers.Select(dtoOffer => new
                {
                    __LastAction = dtoOffer.Actions.OrderByDescending(a => a.TimeCreatedUtc).FirstOrDefault(),
                    Id = dtoOffer.Id
                })
                .Select(dtoLet => new OfferDto()
                {
                    Id = dtoLet.Id,
                    LastAction = dtoLet.__LastAction == null ? null : new OfferActionDto()
                    {
                        Action = dtoLet.__LastAction.Action,
                        TimeCreatedUtc = dtoLet.__LastAction.TimeCreatedUtc,
                        // IF THIS LINE IS COMMENTED OUT, QUERY WILL WORK IN BOTH SQL AND INMEMORY
                        AnyEstablished = dtoLet.__LastAction.Offer.Actions.Any(a => a.Action == OfferActions.Established)
                    }
                });
```

Then I get the following exceptions:

```c#
// INMEMORY: System.ArgumentNullException: 'Value cannot be null.'
// SQL (without QueryClientEvaluationWarning): System.ArgumentNullException: 'Value cannot be null.'
// SQL (with QueryClientEvaluationWarning): System.InvalidOperationException: 'Error generated for warning 'Microsoft.EntityFrameworkCore.Query.QueryClientEvaluationWarning: The LINQ expression 'where (Convert([a].Action, Int32) == 1)' could not be translated and will be evaluated locally.'. 
```

### Reproducible gist

I have created the following gist that successfully reproduces the variation of exceptions with minimal example code - both using SQL and InMemory providers. Please run the provided code to see the different exceptions thrown.

https://gist.github.com/joakimriedel/f716b518572117f64aeb31eaa39ea850

### Further technical details
EF Core version: 2.1.2
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017 15.8.2

**Comment by jcemoller** [comment]
I'm sorry @ajcvickers, but I am not able to reproduce this exact error message anymore. It was something that occurred while debugging another issue (https://github.com/aspnet/EntityFrameworkCore/issues/12148#issuecomment-419079239) and looking at the code now again this my attempt to convert from AutoMapper to EF Core was not done properly.

I have updated this issue with a new gist that successfully reproduces errors for both InMemory and SQL providers, even though the exceptions vary between the providers. See https://gist.github.com/jcemoller/f716b518572117f64aeb31eaa39ea850.

Issue https://github.com/aspnet/EntityFrameworkCore/issues/12148 is probably, but not certainly, related.

**Comment by jcemoller** [comment]
@ajcvickers I must have been a bit tired yesterday. When creating the gist, I forgot to enable *QueryClientEvaluationWarning*. Just updated the gist, and it will now throw the same exception I observed in my actual project for the SQL provider:

*"Microsoft.EntityFrameworkCore.Query.QueryClientEvaluationWarning: The LINQ expression 'where (Convert([a].Action, Int32) == 1)' could not be translated and will be evaluated locally."*

InMemory provider will throw *"System.ArgumentNullException: 'Value cannot be null.'"*

**Comment by jcemoller** [comment]
It's been a year, and I'm still holding my thumbs for this to be fixed for 3.1 LTS.

Revisited this gist with 3.1.0-preview2.19517.13, and it's still failing but now with a different exception message:

```c#
System.InvalidOperationException
  HResult=0x80131509
  Message=Processing of the LINQ expression '(MaterializeCollectionNavigation(
    navigation: Navigation: Offer.Actions,
    subquery: (NavigationExpansionExpression
        Source: DbSet<OfferAction>
            .Where(o3 => Property<Nullable<int>>(o, "Id") != null && Property<Nullable<int>>(o, "Id") == Property<Nullable<int>>(o3, "OfferId"))
            .OrderByDescending(o3 => o3.TimeCreatedUtc)
        PendingSelector: o3 => (NavigationTreeExpression
            Value: (EntityReference: OfferAction)
            Expression: o3).Offer
        CardinalityReducingMethod: FirstOrDefault
    )
        .Where(i => Property<Nullable<int>>((NavigationTreeExpression
            Value: (EntityReference: Offer)
            Expression: o), "Id") != null && Property<Nullable<int>>((NavigationTreeExpression
            Value: (EntityReference: Offer)
            Expression: o), "Id") == Property<Nullable<int>>(i, "OfferId")))
    .AsQueryable()
    .OrderByDescending(a => a.TimeCreatedUtc)
    .Select(s => s.Offer)
    .FirstOrDefault().Actions
    .AsQueryable()' by 'NavigationExpandingExpressionVisitor' failed. This may indicate either a bug or a limitation in EF Core. See https://go.microsoft.com/fwlink/?linkid=2101433 for more detailed information.
  Source=Microsoft.EntityFrameworkCore
  StackTrace:
   at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberAssignment(MemberAssignment node)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberBinding(MemberBinding node)
   at System.Linq.Expressions.ExpressionVisitor.Visit[T](ReadOnlyCollection`1 nodes, Func`2 elementVisitor)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberInit(MemberInitExpression node)
   at System.Linq.Expressions.MemberInitExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitConditional(ConditionalExpression node)
   at System.Linq.Expressions.ConditionalExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberAssignment(MemberAssignment node)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberBinding(MemberBinding node)
   at System.Linq.Expressions.ExpressionVisitor.Visit[T](ReadOnlyCollection`1 nodes, Func`2 elementVisitor)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberInit(MemberInitExpression node)
   at System.Linq.Expressions.MemberInitExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.ExpandNavigationsInExpression(NavigationExpansionExpression source, Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.PendingSelectorExpandingExpressionVisitor.Visit(Expression expression)
   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitArguments(ExpressionVisitor visitor, IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.PendingSelectorExpandingExpressionVisitor.Visit(Expression expression)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberAssignment(MemberAssignment node)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberBinding(MemberBinding node)
   at System.Linq.Expressions.ExpressionVisitor.Visit[T](ReadOnlyCollection`1 nodes, Func`2 elementVisitor)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberInit(MemberInitExpression node)
   at System.Linq.Expressions.MemberInitExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.PendingSelectorExpandingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.PendingSelectorExpandingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.ExpandAndReduce(Expression query, Boolean applyInclude)
   at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.Expand(Expression query)
   at Microsoft.EntityFrameworkCore.Query.QueryTranslationPreprocessor.Process(Expression query)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass12_0`1.<ExecuteAsync>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetAsyncEnumerator(CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.ConfiguredCancelableAsyncEnumerable`1.GetAsyncEnumerator()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.<ToListAsync>d__64`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at EfCoreBug.Program.<Main>d__0.MoveNext() in C:\Users\Joakim\Source\Repos\EfCoreBug\AutoMapperBug\Program.cs:line 61
```

**Comment by smitpatel** [comment]
Both queries fails in SqlServer with #18888 
Both fails in InMemory #19214

**Comment by smitpatel** [comment]
Note to implementer: 
This should be working for relational providers. Verify-fixed.
For InMemory if it does not work then file a new issue.

**Comment by joakimriedel** [comment]
@smitpatel tried with 5.0.0-preview.3.20181.2 still fails with below call stack

# SqlServer
```
System.InvalidOperationException
  HResult=0x80131509
  Message=When called from 'VisitLambda', rewriting a node of type 'System.Linq.Expressions.ParameterExpression' must return a non-null value of the same type. Alternatively, override 'VisitLambda' and change it to not visit children of this type.
  Source=System.Linq.Expressions
  StackTrace:
   at System.Linq.Expressions.ExpressionVisitor.VisitAndConvert[T](T node, String callerName)
   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitParameters(ExpressionVisitor visitor, IParameterProvider nodes, String callerName)
   at System.Linq.Expressions.ExpressionVisitor.VisitLambda[T](Expression`1 node)
   at System.Linq.Expressions.Expression`1.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.Visit(Expression expression)
   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitArguments(ExpressionVisitor visitor, IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.VisitMemberAssignment(MemberAssignment memberAssignment)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberBinding(MemberBinding node)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.VisitMemberInit(MemberInitExpression memberInitExpression)
   at System.Linq.Expressions.MemberInitExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.Visit(Expression expression)
   at System.Linq.Expressions.ExpressionVisitor.VisitConditional(ConditionalExpression node)
   at System.Linq.Expressions.ConditionalExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.VisitMemberAssignment(MemberAssignment memberAssignment)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberBinding(MemberBinding node)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.VisitMemberInit(MemberInitExpression memberInitExpression)
   at System.Linq.Expressions.MemberInitExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.Translate(SelectExpression selectExpression, Expression expression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.TranslateSelect(ShapedQueryExpression source, LambdaExpression selector)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.TranslateSubquery(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.RelationalSqlTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.RelationalSqlTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.RelationalSqlTranslatingExpressionVisitor.Translate(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.VisitMemberAssignment(MemberAssignment memberAssignment)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberBinding(MemberBinding node)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.VisitMemberInit(MemberInitExpression memberInitExpression)
   at System.Linq.Expressions.MemberInitExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.Translate(SelectExpression selectExpression, Expression expression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.TranslateSelect(ShapedQueryExpression source, LambdaExpression selector)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass12_0`1.<ExecuteAsync>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetAsyncEnumerator(CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.ConfiguredCancelableAsyncEnumerable`1.GetAsyncEnumerator()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.<ToListAsync>d__65`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at EfCoreBug.Program.<Main>d__0.MoveNext() in C:\Users\Jocke\Repos\EFCore\13220\Program.cs:line 61
```

# InMemory
```
System.ArgumentNullException
  HResult=0x80004003
  Message=Value cannot be null. 
  Source=System.Linq.Expressions
  StackTrace:
   at System.Linq.Expressions.Expression.ValidateMemberInitArgs(Type type, ReadOnlyCollection`1 bindings)
   at System.Linq.Expressions.Expression.MemberInit(NewExpression newExpression, IEnumerable`1 bindings)
   at System.Linq.Expressions.MemberInitExpression.Update(NewExpression newExpression, IEnumerable`1 bindings)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberInit(MemberInitExpression node)
   at System.Linq.Expressions.MemberInitExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryExpressionTranslatingExpressionVisitor.VisitConditional(ConditionalExpression conditionalExpression)
   at System.Linq.Expressions.ConditionalExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryExpressionTranslatingExpressionVisitor.Translate(Expression expression)
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryProjectionBindingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryProjectionBindingExpressionVisitor.VisitMemberAssignment(MemberAssignment memberAssignment)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberBinding(MemberBinding node)
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryProjectionBindingExpressionVisitor.VisitMemberInit(MemberInitExpression memberInitExpression)
   at System.Linq.Expressions.MemberInitExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryProjectionBindingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryProjectionBindingExpressionVisitor.Translate(InMemoryQueryExpression queryExpression, Expression expression)
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryQueryableMethodTranslatingExpressionVisitor.TranslateSelect(ShapedQueryExpression source, LambdaExpression selector)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass12_0`1.<ExecuteAsync>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetAsyncEnumerator(CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.ConfiguredCancelableAsyncEnumerable`1.GetAsyncEnumerator()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.<ToListAsync>d__65`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at EfCoreBug.Program.<Main>d__0.MoveNext() in C:\Users\Jocke\Repos\EFCore\13220\Program.cs:line 66

  This exception was originally thrown at this call stack:
    [External Code]
    EfCoreBug.Program.Main(string[]) in Program.cs
```

**Comment by joakimriedel** [comment]
@smitpatel have different workarounds all over the code base to prevent this bug, but would very much like to be able to skip them for performance and code clarity reasons. Almost going for two years since issue created, could I assist in any way to get this patched in 3.1 or 5.0?

**Comment by smitpatel** [comment]
The last errors indicate client evaluation encountered where we cannot translate it further.

**Comment by joakimriedel** [comment]
@smitpatel workaround I have in place is to replace `FirstOrDefault()` call with `Take(1)` and then `SingleOrDefault()` on the array with a single item. But would prefer if it would work with `FirstOrDefault` directly.

**Comment by joakimriedel** [comment]
Hey EF Core team, what's the progress here? I see you're making loads of great new features on 5.0, but what about these small query bugs that you stumble upon every time a project goes moderately complex.

This particular case has been bugging me crazy for the last two years. It is about not being able to use `FirstOrDefault()` after `OrderByDescending()` to retrieve a single item `T` from database, instead I have to use `Take(1)` and send the results to an `ICollection<T>` and afterwards pick the single item from the collection... 

It did not get fixed in 2.2, not in 3.0, not in 3.1. What about 5.0?

ping @smitpatel @ajcvickers

**Comment by smitpatel** [comment]
@joakimriedel - Submitted PR. This will be fixed in 5.0.

**Comment by joakimriedel** [comment]
Thanks @smitpatel look forward to testing this with the nightly as soon it's merged.
