### ISSUE TITLE
Projection fails when using oData $expand=X($select=Y) when having nullable foreign keys together with DTO projection

### ISSUE THREAD

**Issue by stefarv** [dotnet/efcore#14321]
Expanding optional navigation properties through oData fails for rows with null value in navigation property together with DTO projection

Skipping DTOs and returning IQueryable of model instead of IQueryable of DTO works without problems

The following query works fine
http://localhost:5000/odata/Products?$expand=Category

```json
{
  "@odata.context": "http://localhost:5000/odata/$metadata#Products",
  "value": [
    {
      "ID": 1,
      "ArticleNumber": "01",
      "Name": "Key ring",
      "Category": null
    },
    {
      "ID": 2,
      "ArticleNumber": "02",
      "Name": "Football shoes Score",
      "Category": {
        "ID": 1,
        "Name": "Shoes"
      }
    }
  ]
}
```

But when selecting only name from category, the problem occurs
http://localhost:5000/odata/Products?$expand=Category($select=Name)
BANG!!! See exception below

However filtering so that the result only contains the second product(that has a category) works fine with $expand=Category($select=Name)
http://localhost:5000/odata/Products?$filter=ID%20eq%202&$expand=Category($select=Name)

```json
{
  "@odata.context": "http://localhost:5000/odata/$metadata#Products(Category(Name))",
  "value": [
    {
      "ID": 2,
      "ArticleNumber": "02",
      "Name": "Football shoes Score",
      "Category": {
        "Name": "Shoes"
      }
    }
  ]
}
```

Versions used
Microsoft.AspNetCore.App 2.0.0
Microsoft.AspNetCore.OData 7.1.0
Microsoft.EntityFrameworkCore 2.2.0
Microsoft.EntityFrameworkCore.SqlServer 2.2.0

```
Console output:

      SELECT [p].[ID], [p].[ArticleNumber], [p].[Name], CASE
          WHEN [p].[CategoryID] IS NULL
          THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT)
      END, [p].[CategoryID] AS [ID0], [p.Category].[Name] AS [Name0]
      FROM [Products] AS [p]
      LEFT JOIN [ProductCategory] AS [p.Category] ON [p].[CategoryID] = [p.Category].[ID]

fail: Microsoft.EntityFrameworkCore.Query[10100]
      An exception occurred while iterating over the results of a query for context type 'EfCoreProjectionBugWeb.Models.ProductContext'.
      System.NullReferenceException: Object reference not set to an instance of an object.
         at lambda_method(Closure , QueryContext , TransparentIdentifier`2 )
         at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.ProjectionShaper.TypedProjectionShaper`3.Shape(QueryContext queryContext, ValueBuffer& valueBuffer)
         at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(DbContext _, Boolean buffer)
         at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
         at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
         at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()

System.NullReferenceException: Object reference not set to an instance of an object.
   at lambda_method(Closure , QueryContext , TransparentIdentifier`2 )
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.ProjectionShaper.TypedProjectionShaper`3.Shape(QueryContext queryContext, ValueBuffer& valueBuffer)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(DbContext _, Boolean buffer)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()

info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
      Executed action EfCoreProjectionBugWeb.Controllers.ProductsController.Get(EfCoreProjectionBugWeb) in 126.6902ms
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
System.NullReferenceException: Object reference not set to an instance of an object.
   at lambda_method(Closure , QueryContext , TransparentIdentifier`2 )
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.ProjectionShaper.TypedProjectionShaper`3.Shape(QueryContext queryContext, ValueBuffer& valueBuffer)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(DbContext _, Boolean buffer)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at Microsoft.AspNet.OData.Formatter.Serialization.ODataResourceSetSerializer.WriteResourceSet(IEnumerable enumerable, IEdmTypeReference resourceSetType, ODataWriter writer, ODataSerializerContext writeContext)
   at Microsoft.AspNet.OData.Formatter.ODataOutputFormatterHelper.WriteToStream(Type type, Object value, IEdmModel model, ODataVersion version, Uri baseAddress, MediaTypeHeaderValue contentType, IWebApiUrlHelper internaUrlHelper, IWebApiRequestMessage internalRequest, IWebApiHeaders internalRequestHeaders, Func`2 getODataMessageWrapper, Func`2 getEdmTypeSerializer, Func`2 getODataPayloadSerializer, Func`1 getODataSerializerContext)
   at Microsoft.AspNet.OData.Formatter.ODataOutputFormatter.WriteResponseBodyAsync(OutputFormatterWriteContext context, Encoding selectedEncoding)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultAsync(IActionResult result)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResultFilterAsync[TFilter,TFilterAsync]()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResultExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultFilters()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
warn: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[2]
      The response has already started, the error page middleware will not be executed.
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HLJIA595EKBG", Request id "0HLJIA595EKBG:00000003": An unhandled exception was thrown by the application.
System.NullReferenceException: Object reference not set to an instance of an object.
   at lambda_method(Closure , QueryContext , TransparentIdentifier`2 )
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.ProjectionShaper.TypedProjectionShaper`3.Shape(QueryContext queryContext, ValueBuffer& valueBuffer)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(DbContext _, Boolean buffer)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at Microsoft.AspNet.OData.Formatter.Serialization.ODataResourceSetSerializer.WriteResourceSet(IEnumerable enumerable, IEdmTypeReference resourceSetType, ODataWriter writer, ODataSerializerContext writeContext)
   at Microsoft.AspNet.OData.Formatter.ODataOutputFormatterHelper.WriteToStream(Type type, Object value, IEdmModel model, ODataVersion version, Uri baseAddress, MediaTypeHeaderValue contentType, IWebApiUrlHelper internaUrlHelper, IWebApiRequestMessage internalRequest, IWebApiHeaders internalRequestHeaders, Func`2 getODataMessageWrapper, Func`2 getEdmTypeSerializer, Func`2 getODataPayloadSerializer, Func`1 getODataSerializerContext)
   at Microsoft.AspNet.OData.Formatter.ODataOutputFormatter.WriteResponseBodyAsync(OutputFormatterWriteContext context, Encoding selectedEncoding)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultAsync(IActionResult result)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResultFilterAsync[TFilter,TFilterAsync]()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResultExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultFilters()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 200.3237ms 200 application/json; odata.metadata=minimal; odata.streaming=true; charset=utf-8
```

### Steps to reproduce
Create DB tables
================

```sql
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ProductCategory](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](max) NULL,
 CONSTRAINT [PK_ProductCategory] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

CREATE TABLE [dbo].[Products](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ArticleNumber] [nvarchar](max) NULL,
	[Name] [nvarchar](max) NULL,
	[CategoryID] [int] NULL,
 CONSTRAINT [PK_Products] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

ALTER TABLE [dbo].[Products]  WITH CHECK ADD  CONSTRAINT [FK_Products_ProductCategory_CategoryID] FOREIGN KEY([CategoryID])
REFERENCES [dbo].[ProductCategory] ([ID])
GO

ALTER TABLE [dbo].[Products] CHECK CONSTRAINT [FK_Products_ProductCategory_CategoryID]
GO
```

================

Seed database tables (one product with value for CategoryID and one with NULL)

```sql
INSERT ProductCategory (name) 
VALUES ('Shoes')

INSERT Products (ArticleNumber, Name, CategoryID)
VALUES ('01', 'Key ring', null)

INSERT Products (ArticleNumber, Name, CategoryID)
VALUES ('02', 'Fotball shoes Score', 1)
```
================

```c#
    public class ProductsController : ODataController
    {
        private ProductContext _dbContext;
        private readonly IMapper _mapper;

        public ProductsController(ProductContext dbContext, IMapper mapper)
        {
            _dbContext = dbContext;
            _mapper = mapper;
        }

        [EnableQuery]
        public IActionResult Get()
        {
            //return Ok(_dbContext.Products.ProjectTo<ProductDto>());

            return Ok(_dbContext.Products.Select(p =>
                new ProductDto {
                    ID = p.ID,
                    ArticleNumber = p.ArticleNumber,
                    Name = p.Name, Category = 
                    p.Category == null ? null : new ProductCategoryDto { ID = p.Category.ID, Name = p.Category.Name } }
            ));

        }
    }

    public class ProductCategoryDto
    {
        public int ID { get; set; }
        public string Name { get; set; }
    }

    public class ProductDto
    {
        public int ID { get; set; }
        public string ArticleNumber { get; set; }
        public string Name { get; set; }
        public ProductCategoryDto Category { get; set; }
    }

    public class ProductContext : DbContext
    {
        public ProductContext(DbContextOptions<ProductContext> options) : base(options)
        {
        }

        public DbSet<Product> Products { get; set; }
    }

    public class ProductCategory
    {
        public int ID { get; set; }
        public string Name { get; set; }
    }

    public class Product
    {
        public int ID { get; set; }
        public string ArticleNumber { get; set; }
        public string Name { get; set; }
        public ProductCategory Category { get; set; }
    }

    public class Program
    {
        public static void Main(string[] args)
        {
            CreateWebHostBuilder(args).Build().Run();
        }

        public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .UseStartup<Startup>();
    }

    public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            var connectionString = "Server=(LocalDb)\\MSSQLLocalDB;Database=TestProducts;Trusted_Connection=true;MultipleActiveResultSets=true";
            services.AddDbContext<ProductContext>(opt => opt.UseSqlServer(connectionString));
            services.AddOData();
            services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_1);

            ConfigureAutoMapper(services);
        }

        private void ConfigureAutoMapper(IServiceCollection services)
        {
            services.AddAutoMapper();
            Mapper.Initialize(c =>
            {
                c.CreateMap<Product, ProductDto>();
                c.CreateMap<ProductCategory, ProductCategoryDto>();
            }
            );

        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseMvc(b =>
            {
                b.Select().Expand().Filter().OrderBy().MaxTop(100).Count();
                b.MapODataServiceRoute("odata", "odata", GetEdmModel());
            });
        }

        private static IEdmModel GetEdmModel()
        {
            ODataConventionModelBuilder builder = new ODataConventionModelBuilder();
            builder.EntitySet<ProductDto>("Products");
            return builder.GetEdmModel();
        }
    }
```

### Further technical details
EF Core version: 2.2.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 8
IDE: Visual Studio 2017 15.9.4

**Comment by stefarv** [comment]
Would also be good to verify that AutoMapper ProjectTo works, see commented line in Controller Get method

**Comment by smitpatel** [comment]
We believe this is fixed in 3.1 release. Looking at the report, the likely cause of issue is our optimization from Navigation.PK to FK property. Which has been removed in new query pipeline. 

Feel free to reopen the issue if you do not get expected results in EF Core 3.1

**Comment by greg-lomax** [comment]
I can confirm that this is still an issue in 3.1.1

Microsoft Visual Studio Professional 2019 Version 16.4.4
DotNet Core SDK 3.1.101
AutoMapper 9.0.0
AutoMapper.Extensions.Microsoft.DependencyInjection 7.0.0
Microsoft.AspNetCore.OData 7.3.0
Microsoft.EntityFrameworkCore 3.1.1
Microsoft.EntityFrameworkCore.SqlServer 3.1.1

**Comment by greg-lomax** [comment]
Using Microsoft.EntityFrameworkCore 3.1.2, I tried removing the null check in the ProductCategoryDto expansion and got a valid result with a null category for the first object and populated for the second.

Should the expansion be conditional (as shown above) or is that no longer necessary?  Does ef just use the expression path when it is needed from a specific select or a default select all?

**Comment by ajcvickers** [comment]
@maumar to give this a try on 3.1.

**Comment by ajcvickers** [comment]
@maumar Ping

**Comment by maumar** [comment]
still gives error.

Initial query:

```
DbSet<Product>
    .Select(p => new ProductDto{ 
        ID = p.ID, 
        ArticleNumber = p.ArticleNumber, 
        Name = p.Name, 
        Category = p.Category == null ? null : new ProductCategoryDto{ 
            ID = p.Category.ID, 
            Name = p.Category.Name 
        }
         
    }
    )
    .Select(namelessParameter{0} => new SelectAllAndExpand<ProductDto>{ 
        ModelID = __TypedProperty_0, 
        Instance = namelessParameter{0}, 
        UseInstanceForProperties = True, 
        Container = new SingleExpandedProperty<SelectSome<ProductCategoryDto>>{ 
            Name = "Category", 
            Value = new SelectSome<ProductCategoryDto>{ 
                ModelID = __TypedProperty_1, 
                Container = new NamedPropertyWithNext0<string>{ 
                    Name = "Name", 
                    Value = namelessParameter{0}.Category.Name, 
                    Next0 = new AutoSelectedNamedProperty<Nullable<int>>{ 
                        Name = "ID", 
                        Value = (Nullable<int>)namelessParameter{0}.Category.ID 
                    }
                     
                }
                 
            }
            , 
            IsNull = (Nullable<int>)namelessParameter{0}.Category.ID == null 
        }
         
    }
    )
```

after processing (before shaper is compiled)

```
(ShapedQueryExpression: 
    QueryExpression: 
        (Projection Mapping:
        SELECT ((p.ID)), ((p.ArticleNumber)), ((p.Name)), (((p0.ID) == (NULL))), ((p0.ID)), ((p0.Name))
        FROM (Products AS p)
        (LEFT JOIN (ProductCategory AS p0) ON ((p.CategoryID) == (p0.ID))))
    ShaperExpression: new SelectAllAndExpand<ProductDto>{ 
            ModelID = RelationalProjectionBindingExpressionVisitor.GetParameterValue<string>(
                queryContext: queryContext, 
                parameterName: "__TypedProperty_0"), 
            Instance = new ProductDto{ 
                ID = (ProjectionBindingExpression: 0), 
                ArticleNumber = (ProjectionBindingExpression: 1), 
                Name = (ProjectionBindingExpression: 2), 
                Category = (ProjectionBindingExpression: 3) ? null : new ProductCategoryDto{ 
                    ID = (ProjectionBindingExpression: 4), 
                    Name = (ProjectionBindingExpression: 5) 
                }
                 
            }
            , 
            UseInstanceForProperties = True, 
            Container = new SingleExpandedProperty<SelectSome<ProductCategoryDto>>{ 
                Name = "Category", 
                Value = new SelectSome<ProductCategoryDto>{ 
                    ModelID = RelationalProjectionBindingExpressionVisitor.GetParameterValue<string>(
                        queryContext: queryContext, 
                        parameterName: "__TypedProperty_1"), 
                    Container = new NamedPropertyWithNext0<string>{ 
                        Name = "Name", 
                        Value = (ProjectionBindingExpression: 3) ? null : new ProductCategoryDto{ 
                            ID = (ProjectionBindingExpression: 4), 
                            Name = (ProjectionBindingExpression: 5) 
                        }
                        .Name, 
                        Next0 = new AutoSelectedNamedProperty<Nullable<int>>{ 
                            Name = "ID", 
                            Value = (Nullable<int>)(ProjectionBindingExpression: 3) ? null : new ProductCategoryDto{ 
                                ID = (ProjectionBindingExpression: 4), 
                                Name = (ProjectionBindingExpression: 5) 
                            }
                            .ID 
                        }
                         
                    }
                     
                }
                , 
                IsNull = (Nullable<int>)(ProjectionBindingExpression: 3) ? null : new ProductCategoryDto{ 
                    ID = (ProjectionBindingExpression: 4), 
                    Name = (ProjectionBindingExpression: 5) 
                }
                .ID == null 
            }
             
        }
)
```

generated sql:

```
SELECT [p].[ID], [p].[ArticleNumber], [p].[Name], CASE
    WHEN [p0].[ID] IS NULL THEN CAST(1 AS bit)
    ELSE CAST(0 AS bit)
END, [p0].[ID], [p0].[Name]
FROM [Products] AS [p]
LEFT JOIN [ProductCategory] AS [p0] ON [p].[CategoryID] = [p0].[ID]
```

results:

ID | ArticleNumber | Name |    | ID  | Name
------------------------------------------------
1       01               Key ring    1   NULL  NULL
2      02                Football... 0   1       Shoes

**Comment by maumar** [comment]
in shaper:
```
                    Container = new NamedPropertyWithNext0<string>{ 
                        Name = "Name", 
                        Value = (ProjectionBindingExpression: 3) ? null : new ProductCategoryDto{ 
                            ID = (ProjectionBindingExpression: 4), 
                            Name = (ProjectionBindingExpression: 5) 
                        }
                        .Name, 
                        Next0 = new AutoSelectedNamedProperty<Nullable<int>>{ 
                            Name = "ID", 
                            Value = (Nullable<int>)(ProjectionBindingExpression: 3) ? null : new ProductCategoryDto{ 
                                ID = (ProjectionBindingExpression: 4), 
                                Name = (ProjectionBindingExpression: 5) 
                            }
                            .ID 
```

we are trying to access .Name and .Id even when the value is null

**Comment by GerjanVlot** [comment]
Any update on this? We can`t use ef core because of this, because all queries with nullable properties with where or order by fail.

**Comment by GerjanVlot** [comment]
I fixed the issue iam not sure if this doesnt break other things but maybe this will help the issue allong.
it basically converts this to "IFF(test, new { Property = "value" }, null).Property" to
"IFF(test, new { Property = "value" }.Property, null)" this.

https://github.com/GerjanVlot/efcore/commit/d791fd5529498a1de9576c8ff4a9e0999216ebf8

**Comment by ajcvickers** [comment]
@GerjanVlot We will investigate this for 5.0, but it may or may not get fixed in 5.0 depending on the outcome of that investigation.

**Comment by GerjanVlot** [comment]
@ajcvickers
Thanks for taking a look at it, found a similar issue https://github.com/dotnet/efcore/issues/21398 probably the same issue.

**Comment by maumar** [comment]
this has been fixed in 7c3a11768e053146e557f8e5fe55d0ede38788e5
closing as dupe of #20711 (even though its the other way around)
