### ISSUE TITLE
The specified deps.json [\\\\TeamDrive\IT\Team Software\Project\etc...] does not exist

### ISSUE THREAD

**Issue by ColemanRocks** [dotnet/efcore#14349]
Our projects execute from a network drive that begins with two slashes. i.e.
"\\\\TeamDrive\IT\..."

When I attempt to run EF Core package manager console commands, it searches for required EF files in the wrong directory: "\\\\\\\\TeamDrive\IT\..."

In this format with four slashes at the beginning of the path, the command is unable to navigate to the file location. I have confirmed that deps.json file exists in the proper location.

### Steps to reproduce
Create a project and database on a drive beginning with two slashes.

Attempt to run EF console commands

### Further technical details
EF Core version: (2.2.1)
Database Provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Operating system: Windows 10 Pro
IDE: (e.g. Visual Studio 2017 15.9.3)

**Comment by ajcvickers** [comment]
From VS Feedback:

when attempting to run any EF commands in the package manager console (scaffold-dbcontext, update-database, etc) it searchs for a file(s) called deps.json and claims it is missing. I have confirmed the file exists in the proper location however Visual Studios is adding additional "\" characters due to improper string handling, thus changing the file path entirely. 

The database being targeted resides on a network drive with a path like: "\\IT\Server2\Team Software"

the error returns that the folder searched was "\\\\IT\Server2\Team Sofware"

As you can see, the string was escaped improperly and added two addition "\" characters.

**Comment by Psypher9** [comment]
This is related to #14781, I'm pretty sure.

**Comment by ajcvickers** [comment]
We can no longer reproduce this and the underlying issue has been fixed. If you are still hitting this issue with EF Core 5.0 or later, then please file a new issue and attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by khanh1nt** [comment]
This issue is still happening

Our projects execute from a network drive that begins with two slashes. i.e.
"\\userdata$\admin..."

When I attempt to run EF Core package manager console commands, it searches for required EF files in the wrong directory: "\\userdata$\admin..."

In this format with four slashes at the beginning of the path, the command is unable to navigate to the file location. I have confirmed that deps.json file exists in the proper location.
(error msg: the specified deps.json [\\\\webserver\userdata$\admin\<prj path>\bin\release\net5.0\demoefcore.deps.json] doesn't exist)

Steps to reproduce
Create a project and database on a drive beginning with two slashes.

Attempt to run Scaffold-dbcontext 

Further technical details
EF Core version: (5.0)
Database Provider:  Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10 Pro
IDE: (Visual Studio 2019 community 16.11.1)

P/s: this worked perfectly on local drive.
