### ISSUE TITLE
Question - Mono support for SSL encryption between client and server

### ISSUE THREAD

**Issue by jsacapdev** [dotnet/efcore#1961]
Please label as a question.

On a docker container, running mono-4.1, when attempting to communicate with a SQL Server (SQL Azure), the following error is raised:

---

2015-03-31T11:24:36.116393500Z System.NotImplementedException: SSL encryption for data sent between client and server is not implemented.
2015-03-31T11:24:36.116423200Z at System.Data.SqlClient.SqlConnection.SetProperties (string,string) <0x00e7b>
2015-03-31T11:24:36.116457900Z at System.Data.SqlClient.SqlConnection.SetConnectionString (string) <0x00357>
2015-03-31T11:24:36.116486200Z at System.Data.SqlClient.SqlConnection.set_ConnectionString (string) <0x0002b>
2015-03-31T11:24:36.116513600Z at System.Data.SqlClient.SqlConnection..ctor (string) <0x00028>
2015-03-31T11:24:36.116543100Z at (wrapper remoting-invoke-with-check) System.Data.SqlClient.SqlConnection..ctor (string) <0x0003b>
2015-03-31T11:24:36.116570300Z at Microsoft.Data.Entity.SqlServer.SqlServerConnection.CreateDbConnection () <0x0003f>
2015-03-31T11:24:36.116597600Z at Microsoft.Data.Entity.Utilities.LazyRef1<System.Data.Common.DbConnection>.get_Value () <0x0002f>
2015-03-31T11:24:36.116624800Z at Microsoft.Data.Entity.Relational.RelationalConnection.Open () <0x00023>
2015-03-31T11:24:36.116674400Z at Microsoft.Data.Entity.Relational.Query.QueryingEnumerable1/Enumerator<Microsoft.Data.Entity.Query.QuerySourceScope1<a5mvc6ef7.Models.C
ourse>>.MoveNext () <0x00053>
2015-03-31T11:24:36.116703900Z at System.Linq.Enumerable/<SelectManyIterator>c__Iterator22<Microsoft.Data.Entity.Query.QuerySourceScope, Microsoft.Data.Entity.Query.Quer
ySourceScope>.MoveNext () <0x0032e>
2015-03-31T11:24:36.116733300Z at System.Linq.Enumerable/WhereSelectEnumerableIterator2<Microsoft.Data.Entity.Query.QuerySourceScope, a5mvc6ef7.Models.Course>.MoveNext (
) <0x001a2>
2015-03-31T11:24:36.116768500Z at System.Linq.Enumerable.FirstOrDefault<a5mvc6ef7.Models.Course> (System.Collections.Generic.IEnumerable1<a5mvc6ef7.Models.Course>) <0x00
0be>
2015-03-31T11:24:36.116796700Z at (wrapper dynamic-method) object.lambda_method (System.Runtime.CompilerServices.Closure) <0x00369>
2015-03-31T11:24:36.116827700Z at Microsoft.Data.Entity.Query.LinqOperatorProvider/ExceptionInterceptor1/EnumeratorExceptionInterceptor<a5mvc6ef7.Models.Course>.MoveNext
 () <0x00044>

---

I appreciated that SSL encryption for data sent between client and server is not yet supported for mono, but the question that I have is will this support be added once ASP.NET 5 / Entity Framework 7 goes live, or is it anywhere with the development roadmap?

**Comment by rowanmiller** [comment]
Support for SSL in Mono is tracked in the Mono project issue tracker here https://bugzilla.xamarin.com/show_bug.cgi?id=25491.

**Comment by rowanmiller** [comment]
BTW the .NET team is also working on getting CoreCLR working on Mac and Linux. When it is ready that will give a .NET runtime that has better parity with .NET on Windows. You can read more about it here http://blogs.msdn.com/b/dotnet/archive/2015/02/26/net-core-open-source-update-february-26-2015.aspx.

**Comment by jsacapdev** [comment]
Resolved.

**Comment by bumblebeeman** [comment]
This has been marked as resolved, but I am still having this issue.

Any advice? Do I need a particular version or something?

**Comment by natemcmaster** [comment]
Don't use Mono if you need encrypted SqlClient connections as https://bugzilla.xamarin.com/show_bug.cgi?id=25491 is still unresolved. Use CoreCLR instead. You can read more about it in http://blogs.msdn.com/b/webdev/archive/2015/11/18/announcing-asp-net-5-release-candidate-1.aspx under the section "Cross-platform SQL Client"

**Comment by bumblebeeman** [comment]
Got you, cool, thanks!
