### ISSUE TITLE
Remove-Migration does not remove last migration and does not restore ModelSnapshot

### ISSUE THREAD

**Issue by MichaelPruefer** [dotnet/efcore#21146]
I have an asp.net core web api with 2 Contexts 

when running (Package Manager Console)
add-migration Test -context AppIdentityDbContext
and then
remove-migration -context AppIdentityDbContext

the generated migration file still exists

The verbose output from remove-migration ends with:

```
Executing 456 update commands as a batch.
A manual migration deletion was detected.
Reverting model snapshot.
Done.
'AppIdentityDbContext' disposed.
```

When there are real model changes and the modelsnapshot is changed, remove-migration does not revert those changes.

Changes that are generated (every time) are e.g.:
```c#
migrationBuilder.UpdateData(
                table: "AspNetRoles",
                keyColumn: "Id",
                keyValue: new Guid("5de8d15a-02c5-4042-b7ed-a4a77f5a8f3a"),
                columns: new[] { "CreatedAtUtc", "ModifiedAtUtc" },
                values: new object[] { new DateTime(2019, 6, 1, 10, 0, 0, 0, DateTimeKind.Utc), new DateTime(2019, 6, 1, 10, 0, 0, 0, DateTimeKind.Utc) });
```
CreatedAtUtc, ModifiedAtUtc are additional properties on our custom Role class which is derived from ```IdentityRole<Guid>```.
These values are generated from DateTime.Parse(...) and then spcifing DateTimeKind.Utc

And everytime i add a new migration i get the same changes to be applied

### Further technical details
dotnet core skd: 3.1.300
EF Core version: 3.1.4
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.1)
Operating system: Windows 10
IDE: Visual Studio 2019 16.6.1

**Comment by ajcvickers** [comment]
Related to #20666 and #18943 and many closed duplicates of these, but non seem to be exactly the same case.

**Comment by MichaelPruefer** [comment]
Postpone it to a 5.0.0 Milestone is a real bad thing for me. 
At the moment a empty migration will generate 10k lines of rubbish.

If i have a real migration with updated columns, data etc. it will be horrible to find these real changes an double check if they are correct.

So why will it fixed that late?

**Comment by ajcvickers** [comment]
@MichaelPruefer See the [release planning process](https://docs.microsoft.com/en-us/ef/core/what-is-new/release-planning).

**Comment by MichaelPruefer** [comment]
Updated some other project from EF Core 2.2.6 to EF Core 3.1.5
First Add-Migration produces same changes as mentioned above, including some of 
```csharp
migrationBuilder.AlterColumn<DateTime>(
                name: "ModifiedAtUtc",
                table: "Regions",
                nullable: false,
                oldClrType: typeof(DateTime),
                oldDefaultValueSql: "GETUTCDATE()");
```
A second Add-Migration produces same changes like the migration before but without the AlterColumn statements.

![grafik](https://user-images.githubusercontent.com/217915/85369971-522c9d00-b52e-11ea-8ca0-be432ed3f3a1.png)
In this image you can see default values being updated. These update statements are now in every migration i create.
It's made of the second migration, directly run after the first run. 12k lines, 6k lines up, 6k down, pulluting our versioning.

Both migrations can't be undone with remove-migration.

Running remove-migration with `-verbose` I'm getting following output:
```
A manual migration deletion was detected.
```
But I have not deleted any migration manually.

The Column definition for ModifiedAtUtc is like
```csharp
	builder.Property(p => p.ModifiedAtUtc).IsRequired().HasDefaultValueSql("GETUTCDATE()");
```
The Column definiiton for IsExportAllowed is like
```csharp
	builder.Property(p => p.IsExportAllowed).HasDefaultValue(false).IsRequired();
```

**Comment by MichaelPruefer** [comment]
Can confirm that in EF Core 3.0.3 everything works as expected.
With 3.1.0 i have the problems mentioned above.

**Comment by MichaelPruefer** [comment]
@ajcvickers I have a big problem:
because of #21146 (this bug) i can't use 3.1.x
because of #17422 i can't use 3.0.x
and no defnitive decision whether #21146 will be fixed in 3.1.x although 3.1 is a LTS release

**Comment by stephan-bauer-hetras** [comment]
The problem seems to be even worse. If there are multiple migrations in a project and the last one is removed as mentioned above the migration still exists AND in model context snapshot the changes from second last migration are reverted. Everytime the snapshot model context needs to be modified manually which is a potential risk for errors.
To the discussion above I think fixing a bug should be part of a patch release. We are talking here about functionality which isn't working as intended!

**Comment by AndriySvyryd** [comment]
The redundant `UpdateData` is fixed in https://github.com/dotnet/efcore/commit/a8f0f4c4dfc94975bd318a6b5a5d3a627df1d5ba

**Comment by bricelam** [comment]
@MichaelPruefer Could you share a repro project so I can investigate the remaining issues you mention?

**Comment by MichaelPruefer** [comment]
@bricelam I will do that in the next days

**Comment by brentbordelon** [comment]
Postponing any bug fix until 5.0 milestone should not be an option - 3.1 is LTS, and that means bug fixes.

**Comment by bricelam** [comment]
> A manual migration deletion was detected.
> Reverting model snapshot.

The redundant UpdateData was also confusing Remove-Migration. Both issues should be fixed now.

**Comment by tamirzamo** [comment]
After upgrading to latest .net core nuget packages, still having this issue.

When I Remove-Migration -Verbose, I get the "A manual migration deletion was detected." message,
And the migration is not removed from the snapshot + the migration file is not deleted.

Will appreciate any direction @bricelam

**Comment by TadGhostal66** [comment]
I assume this fix will be ported into 3.1, correct?

**Comment by ajcvickers** [comment]
@TadGhostal66 We currently have no plans to port this fix to 3.1. See [release planning](https://docs.microsoft.com/en-us/ef/core/what-is-new/release-planning) for more details.

**Comment by TadGhostal66** [comment]
Looking at the LTS policy vs Release Planning, it appears that there is little difference, and therefore very little motivation for anyone to upgrade to an LTS version.  This differs from strategy most companies have for LTS versions.

For instance, if an LTS version is "supported" for three years, but that doesn't mean bugs are fixed - why use an LTS version at all?  I could see if it an LTS version was actually more stable than a "normal" version, but LTS versions seem to be designated as such right when they come out, meaning they are just as likely to have as many bugs as any other version that is released.  The only difference seems to be that a "normal" version will get bug fixes (via a new version), but an LTS version might not get bug fixes at all.  This seems to be the opposite of what most folks expect an LTS to be.

We just put forth a huge effort to upgrade from 2.2 to 3.1, and we chose to do it because 3.1 was LTS.  Now, a couple of months in, it looks like some bug fixes are never going to make it to 3.1 - for the entire 3 years of it's support?  I'm not sure what 3 years of supporting a version really entails, other than fixing bugs.

**Comment by bricelam** [comment]
> What does the LTS designation provide that a non-LTS version doesn't?

Security updates for three years.

> What does EOL really mean

No more security updates.

> From what I see, an LTS version is actually worse than a non-LTS version

If it's features and bug fixes you're looking for, I would have to agree with you. Heck, use [the daily builds](https://github.com/dotnet/efcore/blob/main/docs/DailyBuilds.md) if you can live with a bit of churn around new features as we develop them.

> I'd recommend dropping the concept of LTS versions completely, as it seems to do little more than confuse developers

In the past, we've asked the .NET leadership for stronger and more consistent semantics around what LTS means across .NET products. We'll continue to advocate for our users and forward feedback like this along to them.

**Comment by bricelam** [comment]
BTW, there was an interesting discussion around this [on the Entity Framework Community Standup last month](https://youtu.be/b-zTazj2vuI?t=2056).

**Comment by TadGhostal66** [comment]
Thanks for the info and the link.  Good stuff all around.

**Comment by yakeer** [comment]
Also suffering from this bug,
If it was a minor bug, I would understand why it won't be ported to 3.1.
But that's a quite serious one, 
From what I read here, my alternative is to upgrade to 5.0RC.. which seems to be very buggy, in order to be able to continue coding using Migrations.

I would really appreciate if this bugfix could be ported to 3.1. It was only broken in one of the latest minor builds, since it was working fine until not so long ago.

**Comment by ajcvickers** [comment]
@yakeer If you haven't already, then we'd really appreciate it if you could file the bugs you found using RC1 so we can fix them.

We will discuss again porting this to 3.1.

**Comment by yakeer** [comment]
Hey. 
Thanks for the reopen. 

I haven't yet updated to v5, as I'm developing enterprise systems integrated with our hardware, so we have enough bugs already ;)

Once v5 goes stable, I will start porting to it. 

Thanks for the great work!

**Comment by ajcvickers** [comment]
@yakeer In that case can you provide more details on your statement, "which seems to be very buggy?" What is making you believe that?

**Comment by yakeer** [comment]
I take my words back on the "very buggy" part, just was noticing some issues after rc1 release that could definitely affect my systems.

**Comment by TadGhostal66** [comment]
Thanks for reopening.  We made a large, concerted effort to upgrade from 2.x to 3.1, largely for the LTS status, and largely driven by myself.  Unfortunately, this bug got noticed by a few devs about a month in.  I'm _really_ not looking forward to saying, "it'll be fixed once we move to 5".

**Comment by ajcvickers** [comment]
Note from triage: @AndriySvyryd to prepare a 3.1 patch to take for approval.
