### ISSUE TITLE
EF Core 5 RC1 breaks multi-queries with AutoMapper

### ISSUE THREAD

**Issue by BenjaminAbt** [dotnet/efcore#22578]
Multi-Query Expressions with AutoMapper are not working with RC1 anymore.

We use as often as possible a multi-query approach to load data via EF Core from MSSQL.

```
    var q = from _ in _dbContext.Tickets.AsNoTracking()
        select new
        {
            NewestTickets =
                _dbContext.Tickets
                    .Where(ticket => ticket.Group.CategoryId == 1) // demo filter
                    .OrderByDescending(ticket => ticket.Question.CreatedOn)
                    .ProjectTo<TicketIdentityProjection>(_mapper.ConfigurationProvider)
                    .Take(take)
                    .ToList(),
           AnotherPropertyName2 = ExpressionHere2,
           AnotherPropertyName3 = ExpressionHere3,
        };

var r = await q.FirstOrDefaultAsync(cancellationToken).ConfigureAwaitFalse();
```
This worked very good so far and we had great results.
With the latest EF Core 5 RC1 Update we run in dozen of issues like

> InvalidOperationException: The LINQ expression 'DbSet<TicketEntity>()
> .Where(ticket => ticket.Group.CategoryId == 1)
> .OrderByDescending(ticket => ticket.Question.CreatedOn) .ProjectTo(
> configuration: ___mapper_ConfigurationProvider_0, membersToExpand:
> Expression<Func<TicketIdentityProjection, object>>[] { })
> .Take(__take_1)' could not be translated. Either rewrite the query in
> a form that can be translated, or switch to client evaluation
> explicitly by inserting a call to either AsEnumerable(),
> AsAsyncEnumerable(), ToList(), or ToListAsync(). See
> https://go.microsoft.com/fwlink/?linkid=2101038 for more information.

The problem is the projection of AutoMapper, which seems to be incompatible with EF Core now. In the past, it almost didn't matter where we did the projection; the query was actually always generated identically.
Now, however, it seems to be relevant where the projection takes place and how.

So putting the projection after take we get another error:

```
         NewestTickets =
                _dbContext.Tickets
                    .Where(ticket => ticket.Group.CategoryId == 1)
                    .OrderByDescending(ticket => ticket.Question.CreatedOn)
                    .Take(take)
                    .ProjectTo<TicketIdentityProjection>(_mapper.ConfigurationProvider)
                    .ToList(),
```

> An unhandled exception occurred while processing the request.
ArgumentException: Expression of type 'System.Collections.Generic.List`1[Entities.TicketEntity]' cannot be used for parameter of type 'System.Linq.IQueryable' of method 'System.Linq.IQueryable`1[Projections.TicketIdentityProjection] ProjectTo[TicketIdentityProjection](System.Linq.IQueryable, AutoMapper.IConfigurationProvider, System.Linq.Expressions.Expression`1[System.Func`2[Projections.TicketIdentityProjection,System.Object]][])' (Parameter 'arg0')

It should be noted that it is now apparently always necessary to use ToList in the query, which was also not the case in the past.

> An unhandled exception occurred while processing the request.
InvalidOperationException: The query contains a final projection '_ => DbSet<TicketEntity>()
.Where(ticket => ticket.Group.CategoryId == 1)
.OrderByDescending(ticket => ticket.Question.CreatedOn)
.Take(__take_0)
.ProjectTo(
configuration: ___mapper_ConfigurationProvider_1,
membersToExpand: Expression<Func<TicketIdentityProjection, object>>[] { })' to type 'IQueryable<TicketIdentityProjection>'. Collections in the final projection must be an 'IEnumerable<T>' type such as 'List<T>'. Consider using 'ToList()' or some other mechanism to convert the 'IQueryable<T>' or 'IOrderedEnumerable<T>' into an 'IEnumerable<T>'.

This change is apparently the reason: https://github.com/dotnet/efcore/pull/22024

The only possibility at present is a manual mapping and to do without AutoMapper in the query or we dont use multi-queries and fire query-by-query which increases the overhead of latency.

How can AutoMapper be further used with EFCore here?

### Further technical details

EF Core version: 5.0.0-rc.1.20451.13
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: 5.0.100-preview.8.20417.9
Operating system: win10-x64
IDE: Version 16.8.0 Preview 3.0

**Comment by smitpatel** [comment]
You cannot use AutoMapper `ProjectTo` method inside a lambda of a query. You must have to use AutoMapper on top level to map the whole graph of output object. When you put it inside a lambda the method won't be executed actually and it will be made part of the query. That is how expression trees work. EF cannot see what is inside a method so ProjectTo has to be invoked on client side.
In case 1 there is Take after client method so you get error that query cannot be translated.
In case 2 since ProjectTo is last projection of subquery, EF Core actually invokes it by passing the list of `TicketElement` but auto mapper expects a `IQueryable<T>` not a list. AutoMapper expect IQueryable since it is supposed to integrate the mapping in the actual expression tree and not evaluate on client side.

This behavior is same for all versions of EF Core. If it worked before 3.1 then it was doing client evaluation which is not supported except last projection since version 3.1

**Comment by BenjaminAbt** [comment]
Thank you for your answer, but unfortunately I cannot relate to it. In all previous versions of EF Core this procedure worked perfectly.
Only since the RC1 this does not work anymore.

If I could really use AutoMapper only at the top level, this would automatically mean that I can only filter and sort according to the criteria I place in the respective projection.
That makes no sense.

ProjectTo also does not lead to a Client-Side Evalutation.
This is the reason why so many use exactly this mechanism.

**Comment by ajcvickers** [comment]
@BenjaminAbt Can you post a runnable repro for this that works on 3.1 and fails on 5.0? That way we can investigate the difference.

**Comment by ajcvickers** [comment]
Note from triage; @maumar is going to try to reproduce the allegedly working query on 3.1 so we can investigate. If we can't make it work on 3.1, then we'll post here showing what we tried.

**Comment by maumar** [comment]
I tried to reverse-engineer the repro based on the information provided and ended up with the following code

```cs
    class Program
    {
        static void Main(string[] args)
        {
            using (var ctx = new MyContext())
            {
                ctx.Database.EnsureDeleted();
                ctx.Database.EnsureCreated();

                var g1 = new Group { CategoryId = 1 };
                var q1 = new Question { CreatedOn = DateTime.Now };
                var g2 = new Group { CategoryId = 1 };
                var q2 = new Question { CreatedOn = DateTime.Now };
                var g3 = new Group { CategoryId = 2 };
                var q3 = new Question { CreatedOn = DateTime.Now };

                var t1 = new Ticket { Group = g1, Question = q1 };
                var t2 = new Ticket { Group = g2, Question = q2 };
                var t3 = new Ticket { Group = g3, Question = q3 };

                ctx.Tickets.AddRange(t1, t2, t3);
                ctx.Groups.AddRange(g1, g2, g3);
                ctx.Questions.AddRange(q1, q2, q3);
                ctx.SaveChanges();

                var take = 10;

                var configuration = new MapperConfiguration(cfg =>
                {
                    cfg.CreateMap<Ticket, TicketIdentityProjection>();
                    cfg.CreateMap<Group, GroupDTO>();
                    cfg.CreateMap<Question, QuestionDTO>();
                });

                var mapper = new Mapper(configuration);

                var q = from _ in ctx.Tickets.AsNoTracking()
                        select new
                        {
                            NewestTickets =
                                ctx.Tickets
                                    .Where(ticket => ticket.Group.CategoryId == 1) // demo filter
                                    .OrderByDescending(ticket => ticket.Question.CreatedOn)
                                    .ProjectTo<TicketIdentityProjection>(mapper.ConfigurationProvider)
                                    .Take(take)
                                    .ToList(),
                        };

                var r = q.FirstOrDefault();


                    var newestTickets =
                        ctx.Tickets
                            .Where(ticket => ticket.Group.CategoryId == 1)
                            .OrderByDescending(ticket => ticket.Question.CreatedOn)
                            .Take(take)
                            .ProjectTo<TicketIdentityProjection>(mapper.ConfigurationProvider)
                            .ToList();
            }
        }
    }

    public class MyContext : DbContext
    {
        public DbSet<Ticket> Tickets { get; set; }
        public DbSet<Question> Questions { get; set; }
        public DbSet<Group> Groups { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=ReproAutoMapper;Trusted_Connection=True;MultipleActiveResultSets=true");
        }
    }

    public class Ticket
    {
        public int Id { get; set; }
        public Group Group { get; set; }
        public Question Question { get; set; }
    }

    public class Group
    {
        public int Id { get; set; }
        public int CategoryId { get; set; }
    }

    public class Question
    {
        public int Id { get; set; }
        public DateTime CreatedOn { get; set; }
    }

    public class TicketIdentityProjection
    {
        public GroupDTO Group { get; set; }

    }

    public class GroupDTO
    {
        public int CategoryId { get; set; }
    }

    public class QuestionDTO
    {
        public DateTime CreatedOn { get; set; }
    }
```

First query fails on 3.1 for me as well throwing the following exception:

```
Processing of the LINQ expression 'DbSet<Ticket>
    .Where(ticket => ticket.Group.CategoryId == 1)
    .OrderByDescending(ticket => ticket.Question.CreatedOn)
    .ProjectTo(
        source: __mapper_ConfigurationProvider_0, 
        configuration: Expression<Func<TicketIdentityProjection, object>>[] { })
    .Take(__take_1)' by 'NavigationExpandingExpressionVisitor' failed. This may indicate either a bug or a limitation in EF Core. See https://go.microsoft.com/fwlink/?linkid=2101433 for more detailed information.

   at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitArguments(ExpressionVisitor visitor, IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitNew(NewExpression node)
   at System.Linq.Expressions.NewExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.PendingSelectorExpandingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.Expand(Expression query)
   at Microsoft.EntityFrameworkCore.Query.QueryTranslationPreprocessor.Process(Expression query)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass9_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.FirstOrDefault[TSource](IQueryable`1 source)
```


second query worked for me for both 3.1 and current bits

code used:

```
                    var newestTickets =
                        ctx.Tickets
                            .Where(ticket => ticket.Group.CategoryId == 1)
                            .OrderByDescending(ticket => ticket.Question.CreatedOn)
                            .Take(take)
                            .ProjectTo<TicketIdentityProjection>(mapper.ConfigurationProvider)
                            .ToList();
```


query plan generated:

```
ShapedQueryExpression: 
    QueryExpression: 
        Projection Mapping:
        SELECT TOP(@__p_0) g.Id == NULL, g.CategoryId, q.Id == NULL, q.CreatedOn
        FROM Tickets AS t
        LEFT JOIN Groups AS g ON t.GroupId == g.Id
        LEFT JOIN Questions AS q ON t.QuestionId == q.Id
        WHERE g.CategoryId == 1
        ORDER BY q.CreatedOn DESC
    ShaperExpression: new TicketIdentityProjection{ 
            Group = ProjectionBindingExpression: 0 == True ? null : new GroupDTO{ CategoryId = (int)ProjectionBindingExpression: 1 }, 
            Question = ProjectionBindingExpression: 2 == True ? null : new QuestionDTO{ CreatedOn = (DateTime)ProjectionBindingExpression: 3 }
        }
```

Failure in the first query is expected since client eval was removed and EF doesn't recognize auto mapper methods in the middle of the query, as @smitpatel pointed out. Wrt second query I must be missing relevant details, so the full repro or additional info would be ideal to move this forward @BenjaminAbt

**Comment by smitpatel** [comment]
Second query is actually this
```C#

                var q = from _ in ctx.Tickets.AsNoTracking()
                        select new
                        {
                            NewestTickets =
                                ctx.Tickets
                                    .Where(ticket => ticket.Group.CategoryId == 1) // demo filter
                                    .OrderByDescending(ticket => ticket.Question.CreatedOn)
                                    .Take(take)
                                    .ProjectTo<TicketIdentityProjection>(mapper.ConfigurationProvider)
                                    .ToList(),
                        };

                var r = q.FirstOrDefault();
```
So with Take moved before ProjectTo which is equivalent of Select, nav expansion will not throw exception. But translation will still try to client evaluate it. When we generate a collection when client evaluating, we create a list of element. But ProjectTo is defined for IQuerable<T> and not List<T>. So in 3.1 it throws argument exception. In 5.0 we improved the exception message to be specific.

**Comment by maumar** [comment]
exception on 3.1:

```
Object reference not set to an instance of an object.

   at Microsoft.EntityFrameworkCore.Query.SqlExpressions.SelectExpression.AddCollectionProjection(ShapedQueryExpression shapedQueryExpression, INavigation navigation, Type elementType)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.VisitNew(NewExpression newExpression)
   at System.Linq.Expressions.NewExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.Translate(SelectExpression selectExpression, Expression expression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.TranslateSelect(ShapedQueryExpression source, LambdaExpression selector)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass9_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
```

**Comment by smitpatel** [comment]
3.1 exception is same as https://github.com/dotnet/efcore/issues/21602 
It could have been fixed or improved in #21502

**Comment by ajcvickers** [comment]
@BenjaminAbt At this point we are out of ideas. Can you post a runnable repro for this that works on 3.1 and fails on 5.0? That way we can investigate the difference.

**Comment by AndriySvyryd** [comment]
**EF Team Triage:** This issue is still lacking enough information for us to be able to effectively triage it. Once you provide a small, runnable project or post a small, runnable code listing that reproduces what you are seeing we can investigate and reopen this issue.
