### ISSUE TITLE
Migration keeps adding columns

### ISSUE THREAD

**Issue by Valdeminas** [dotnet/efcore#24275]
Hi. 

After doing some model changes, add-migration always generates a non-empty Migration file, trying to create the same columns. What is more, add-migration, does not modify the ModelSnapshot,

i.e. if I run two consecutive add-migration's, even without any changes to the model, both of them will generate Migration files with identical code, trying to add columns.

I'm aware that this most likely has something to do with my model set-up, but it is rather complicated and hard to debug.
So, before getting into the specifics of the model, I was hoping, maybe somebody has a pointer a general idea, what could be causing these non-empty migrations to appear, and where should I look to resolve the issue?

Or, am I misunderstanding something, and it is expected, that migrations can be non-empty even without the snapshot being modified?

Thank you.

EF Core version: EF 5
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 5.0
Operating system: Windows
IDE: Visual Studio 2019 16.9

**Comment by Valdeminas** [comment]
Slight Update.

The model I'm working with is roughly equivalent to:

Before (this worked normally)
```
public class Aggregate
{
    public FullAddress FullAddress { get; set; }
    public CityAddress CityAddress { get; set; }
}

public class CityAddress
{
    public string Cap { get; set; }
    public string City { get; set; }
}

public class FullAddress : CityAddress
{
    public string Street { get; set; }
}

protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    modelBuilder.Entity<Aggregate>().OwnsOne(e => e.FullAddress);
    modelBuilder.Entity<Aggregate>().OwnsOne(e => e.CityAddress);
}
 ```
 
 After (this keeps trying to add Aggregate_FullAddress_OwnedProperty_Property and Aggregate_CityAddress_OwnedProperty_Property)
 ```
public class Aggregate
{
    public FullAddress FullAddress { get; set; }
    public CityAddress CityAddress { get; set; }
}

public class CityAddress
{
    public string Cap { get; set; }
    public string City { get; set; }
    public OwnedProperty OwnedProperty { get; set; }
}

public class FullAddress : CityAddress
{
    public string Street { get; set; }
}

[Owned]
public class OwnedProperty
{
    public string Property { get; set; }
}

protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    modelBuilder.Entity<Aggregate>().OwnsOne(e => e.FullAddress);
    modelBuilder.Entity<Aggregate>().OwnsOne(e => e.CityAddress);
}
```

Does this have something to do with Owned Entity Inheritance hierarchies?
And, if so, why did it work before?

Thanks.

**Comment by ajcvickers** [comment]
@Valdeminas I am not able to reproduce this behavior with EF Core 5.0.3. Can you confirm that you are using 5.0.3? If so, and this still isn't working, then please post a full model where you are seeing this. (For example, I had to add a primary key property to the model above, indicating that it is not complete.)

**Comment by Valdeminas** [comment]
Hey.

Sorry. Above was just a rough cut.
I have managed to reproduce the problem using this model:

Note that the problem does not appear, while we only have ```Root.Aggregates```, but once we introduce ```Root.Aggregates2``` the problem appears. Similarly, if  we remove ```Base0.OwnedProp``` from the model, the problem also dissapears.

```
public class Root
    {
        private HashSet<Aggregate> _aggregates;
        private HashSet<Aggregate2> _aggregates2;

        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public virtual string Id { get; protected set; }

        public IEnumerable<Aggregate> Aggregates => _aggregates?.ToList();
        public IEnumerable<Aggregate2> Aggregates2 => _aggregates2?.ToList();
    }

    public class Aggregate
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public virtual Guid Id { get; protected set; }

        public ValueObject ValueObject { get; private set; }
    }

    public class Aggregate2
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public virtual Guid Id { get; protected set; }

        public ValueObject ValueObject { get; private set; }
    }

    public class ValueObject
    {
        public TypeA TypeA { get; private set; }
        public TypeB TypeB { get; private set; }
        public TypeC TypeC { get; private set; }
    }

    public class TypeA : Base1
    {
    }

    public class TypeB : Base1
    {
    }

    public class TypeC : Base0
    {
    }

    public class Base1 : Base0
    {
    }

    public abstract class Base0
    {
        public string SimpleValue { get; protected set; }
        [Required]
        public OwnedProp OwnedProp { get; set; }
    }

    [Owned]
    public class OwnedProp
    {
        public string SimpleValue { get; protected set; }
    }
```

**Comment by Valdeminas** [comment]
Also including the config:

```
public class SchoolContext : DbContext
    {
        public SchoolContext(DbContextOptions<SchoolContext> options) : base(options)
        {
        }

        public DbSet<Aggregate> Aggregate { get; set; }
        public static string Schema = "Aggregate";

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {

            modelBuilder.ApplyConfiguration(new AggregateConfiguration());
            modelBuilder.ApplyConfiguration(new Aggregate2Configuration());
            modelBuilder.ApplyConfiguration(new RootConfiguration());

        }

        public class AggregateConfiguration : IEntityTypeConfiguration<Aggregate>
        {
            public void Configure(EntityTypeBuilder<Aggregate> builder)
            {
                builder.OwnsOne(nav => nav.ValueObject, AIAction =>
                {
                    AIAction.OwnsOne(nav => nav.TypeA);
                    AIAction.OwnsOne(nav => nav.TypeB);
                    AIAction.OwnsOne(nav => nav.TypeC);

                    AIAction.Navigation(nav => nav.TypeA).IsRequired();
                    AIAction.Navigation(nav => nav.TypeB).IsRequired();
                    AIAction.Navigation(nav => nav.TypeC).IsRequired();
                });
                builder.Navigation(e => e.ValueObject).IsRequired();

                builder.ToTable("Aggregates", SchoolContext.Schema);
            }
        }

        public class Aggregate2Configuration : IEntityTypeConfiguration<Aggregate2>
        {
            public void Configure(EntityTypeBuilder<Aggregate2> builder)
            {
                builder.OwnsOne(nav => nav.ValueObject, AIAction =>
                {
                    AIAction.OwnsOne(nav => nav.TypeA);
                    AIAction.OwnsOne(nav => nav.TypeB);
                    AIAction.OwnsOne(nav => nav.TypeC);

                    AIAction.Navigation(nav => nav.TypeA).IsRequired();
                    AIAction.Navigation(nav => nav.TypeB).IsRequired();
                    AIAction.Navigation(nav => nav.TypeC).IsRequired();
                });
                builder.Navigation(e => e.ValueObject).IsRequired();

                builder.ToTable("Aggregates2", SchoolContext.Schema);
            }
        }

        public class RootConfiguration : IEntityTypeConfiguration<Root>
        {
            public void Configure(EntityTypeBuilder<Root> builder)
            {
                var aggregates = builder.Metadata.FindNavigation(nameof(Root.Aggregates));
                aggregates.SetPropertyAccessMode(PropertyAccessMode.Field);

                var aggregates2 = builder.Metadata.FindNavigation(nameof(Root.Aggregates2));
                aggregates2.SetPropertyAccessMode(PropertyAccessMode.Field);

                builder.ToTable("Roots", SchoolContext.Schema);
            }
        }
    }
```

**Comment by bricelam** [comment]
Looks like this has already been fixed in 6.0

**Comment by magiak** [comment]
Hello, will it be fixed for version 5? It is still an issue with latest 5.0.12.

**Comment by ajcvickers** [comment]
@magiak This issue does not meet the bar for fixing in a 5.0.x patch. See [release planning](https://docs.microsoft.com/en-us/ef/core/what-is-new/release-planning) for more information.

**Comment by magiak** [comment]
Hello, I finally updated the EF to EF Core 6.0.1 and it fixed the problem with adding the columns but it still keeps generating DropForeignKey and AddForeignKey.

**Comment by AndriySvyryd** [comment]
@magiak Please file a new issue with a small repro project.
