### ISSUE TITLE
Always encrypted feature is not working when inserting null value for property of type decimal? due to failure when calling sp_describe_parameter_encryption

### ISSUE THREAD

**Issue by tiggris** [dotnet/efcore#24426]
### Sample code 

Sample code could be found here: https://github.com/tiggris/EfCoreAlwaysEncrypted
* SQL server: localdb 
* Key store provider: _SqlColumnEncryptionAzureKeyVaultProvider_ with configuration set in user secrets:
```
{
  "KeyVault:Url": "[key vault url]",
  "KeyVault:KeyName": "[key name]",
  "KeyVault:KeyVersion": "[key version]"
}
```

### Issue description
The root cause of this issue is invalid parameter type provided for _sp_describe_parameter_encryption_ called by SqlClient:
```sql
exec sp_describe_parameter_encryption N'SET NOCOUNT ON;
INSERT INTO [Products] ([Description], [DiscountPercentage], [Name], [Price])
VALUES (@p0, @p1, @p2, @p3);
SELECT [Id]
FROM [Products]
WHERE @@ROWCOUNT = 1 AND [Id] = scope_identity();
',N'@p0 nvarchar(500),@p1 nvarchar(4000),@p2 nvarchar(50),@p3 decimal(10,2)'
```
where @p1 should be of type decimal(5,2) and not nvarchar(4000)

While debugging I was able to figure out that the issue is related to the null value of _TypeMappedRelationalParameter.RelationalTypeMapping.DbType_ in _RelationalTypeMapping.CreateParameter_ method:

```c#
if (DbType.HasValue)
{
    parameter.DbType = DbType.Value;
}
```
where parameter.DbType at this point is string

### Stack trace
 Stack Trace: 
```
    ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
    BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
    RelationalDatabase.SaveChanges(IList`1 entries)
    StateManager.SaveChanges(IList`1 entriesToSave)
    StateManager.SaveChanges(DbContext _, Boolean acceptAllChangesOnSuccess)
    SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
    StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
    DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
    DbContext.SaveChanges()
    AlwaysEncryptedTests.InsertProduct_WhenDiscountIsNull_ShouldNotThrowException() line 26
    ----- Inner Stack Trace -----
    SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
    SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
    TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
    TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
    SqlDataReader.TryConsumeMetaData()
    SqlDataReader.get_MetaData()
    SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
    SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
    SqlCommand.TryFetchInputParameterEncryptionInfo(Int32 timeout, Boolean isAsync, Boolean asyncWrite, Boolean& inputParameterEncryptionNeeded, Task& task, ReadOnlyDictionary`2& describeParameterEncryptionRpcOriginalRpcMap)
    SqlCommand.PrepareForTransparentEncryption(CommandBehavior cmdBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, TaskCompletionSource`1 completion, Task& returnTask, Boolean asyncWrite, Boolean& usedCache, Boolean inRetry)
    SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
    SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
    SqlCommand.ExecuteReader(CommandBehavior behavior)
    SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
    DbCommand.ExecuteReader()
    RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
    ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
```

### Provider and version information

EF Core version: 5.0.4
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.1 (also reproduceable on .NET 5.0)
Operating system: Windows 10
IDE: Visual Studio 2019 16.8.3

**Comment by ajcvickers** [comment]
@tiggris Can you post the output from EF Core logging? It should look something like this:

```
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (17ms) [Parameters=[@p0=NULL (Size = 500), @p1='15.50' (Nullable = true) (Precision = 5) (Scale = 2), @p2='Some product' (Size = 50), @p3='123.00' (Precision = 10) (Scale = 2)], CommandType='Text', CommandTimeout='30']
      SET NOCOUNT ON;
      INSERT INTO [Product] ([Description], [DiscountPercentage], [Name], [Price])
      VALUES (@p0, @p1, @p2, @p3);
      SELECT [Id]
      FROM [Product]
      WHERE @@ROWCOUNT = 1 AND [Id] = scope_identity();

```

**Comment by tiggris** [comment]
Hi @ajcvickers!

Here is the output:

```
Failed executing DbCommand (51ms) [Parameters=[@p0='Some description' (Size = 500), @p1=NULL (Precision = 5) (Scale = 2), @p2='Some product' (Size = 50), @p3='123.00' (Precision = 10) (Scale = 2), @p4='1' (Nullable = true)], CommandType='Text', CommandTimeout='30']
SET NOCOUNT ON;
INSERT INTO [Products] ([Description], [DiscountPercentage], [Name], [Price], [Quantity])
VALUES (@p0, @p1, @p2, @p3, @p4);
SELECT [Id]
FROM [Products]
WHERE @@ROWCOUNT = 1 AND [Id] = scope_identity();
```

I hope it's sufficient. Otherwise please let me know.

**Comment by ajcvickers** [comment]
@maumar As far as I can tell we are creating the parameters with the correct DbType. Can you attempt to reproduce the actual error from SqlClient?

![image](https://user-images.githubusercontent.com/1430078/112205085-ab1a8600-8bd1-11eb-8630-0e7d8d72bf31.png)
![image](https://user-images.githubusercontent.com/1430078/112205156-c08fb000-8bd1-11eb-9158-a187d6a090bf.png)

**Comment by mevans-medpace** [comment]
Is there any known workaround for this problem? We are unable to insert data into a table with encrypted nullable decimal columns.

**Comment by ajcvickers** [comment]
@mevans-medpace Can you try with the latest [EF Core 6.0 daily build](https://github.com/dotnet/efcore/blob/release/6.0/docs/DailyBuilds.md)? We have fixed several bugs in this area for EF Core 6.0.

**Comment by tiggris** [comment]
Unfortunately the issue still persists - just tested on NET Core 6.0 with Microsoft.EntityFrameworkCore & Microsoft.EntityFrameworkCore.SqlServer updated to version 6.0.0.-rc.1.21452.10.

**Comment by ajcvickers** [comment]
@tiggris Yes, but we have fixed several issued _after RC1 was built_. Can you please try with the [daily build](https://github.com/dotnet/efcore/blob/release/6.0/docs/DailyBuilds.md). This will give you version 6.0.0-rtm.21503.1.

**Comment by tiggris** [comment]
You nailed it! It's working :) Tested on version 6.0.0-rtm.21503.1
