### ISSUE TITLE
How to get Point-Read with EF Core 6.0 & CosmosDB, Find & FindAsync methods

### ISSUE THREAD

**Issue by shahabganji** [dotnet/efcore#27679]
## How to get a point read with Find or FindAsync methods.

I saw in the documentations of [What's new? For EF Core 6.0](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-6.0/whatsnew#diagnostics) that a point read could be achieved if `Id` and `PartitionKey` passed to the `Find` method; however, this seems to not be working no matter how the entity ID configured, I tried various configurations, but none worked properly. [This repository](https://github.com/shahabisblogging/EFCore-Array-String/tree/question/point-read) helps to reproduce the issue we have at the Production.

Code sample from Microsoft Documentation:
```cs
var isosceles = context.Triangles.Find("Isosceles", "TrianglesPartition");
```

```bash
info: 8/30/2021 14:53:39.326 CosmosEventId.ExecutingReadItem[30101] (Microsoft.EntityFrameworkCore.Database.Command)
      Reading resource 'Isosceles' item from container 'Shapes' in partition 'TrianglesPartition'.
info: 8/30/2021 14:53:39.330 CosmosEventId.ExecutedReadItem[30103] (Microsoft.EntityFrameworkCore.Database.Command)
      Executed ReadItem (1 ms, 1 RU) ActivityId='3c278643-4e7f-4bb2-9953-6055b5f1288f', Container='Shapes', Id='Isosceles', Partition='TrianglesPartition'
```

<hr />

Followings are two different approaches I tried,
```cs
// omitted code for clarity
  builder.HasKey(p => new {p.Id, p.Owner});
        builder.Property(p => p.Id)
            .ToJsonProperty("id")
            .IsRequired();
        
        builder.HasPartitionKey(p => p.Owner);
        builder.Property(p => p.Owner).IsRequired();
// omitted code for clarity
```

```cs
// omitted code for clarity
   builder.HasKey(p => p.Id);
        builder.Property(p => p.Id)
            .ToJsonProperty("id")
            .IsRequired();
        
        builder.HasPartitionKey(p => p.Owner);
        builder.Property(p => p.Owner).IsRequired();
// omitted code for clarity
```

The latter one, is throwing an exception at runtime if you pass both `Id` and `PartitionKey` mentioning that the entity is configured with one key; this approach might be useful when both the ID and partition key are the same property, tho. It did not work for entities with that condition too, the same property being partition key and id. 

```bash
Unhandled exception. System.ArgumentException: Entity type 'Draft' is defined with a single key property, but 2 values were passed to the 'Find' method.
   at Microsoft.EntityFrameworkCore.Internal.EntityFinder`1.FindTracked(Object[] keyValues, IReadOnlyList`1& keyProperties)
   at Microsoft.EntityFrameworkCore.Internal.EntityFinder`1.FindAsync(Object[] keyValues, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.FindAsync(Object[] keyValues)
   at Program.<Main>$(String[] args) in C:\Users\saeed.ganji\dev\playground\EFCore-Array-String\Sample.EFCore.ArrayPrimitiveTypes\Program.cs:line 37

```

All the time it results to a SQL Query instead of a point read.

```cs
var draft = await context.Drafts.FindAsync(Guid.Parse("4042662c-3b7a-4970-aee5-8bdc6d5e7d1d"), "Sample");
```

```bash
dbug: 3/21/2022 14:20:19.826 CoreEventId.QueryCompilationStarting[10111] (Microsoft.EntityFrameworkCore.Query)
      Compiling query expression:
      'DbSet<Draft>()
          .FirstOrDefault(e => object.Equals(
              objA: EF.Property<object>(e, "Id"),
              objB: (object)__get_Item_0) && EF.Property<string>(e, "Owner") == __p_1)'
dbug: 3/21/2022 14:20:19.917 CoreEventId.QueryExecutionPlanned[10107] (Microsoft.EntityFrameworkCore.Query)
      Generated query execution expression:
      'queryContext => ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync<Draft>(
          asyncEnumerable: new QueryingEnumerable<Draft>(
              (CosmosQueryContext)queryContext,
              SqlExpressionFactory,
              QuerySqlGeneratorFactory,
              [Cosmos.Query.Internal.SelectExpression],
              Func<QueryContext, JObject, Draft>,
              Sample.EFCore.ArrayPrimitiveTypes.Storage.BooksContext,
              null,
              False,
              True
          ),
          cancellationToken: queryContext.CancellationToken)'
info: 3/21/2022 14:20:19.994 CosmosEventId.ExecutingSqlQuery[30100] (Microsoft.EntityFrameworkCore.Database.Command)
      Executing SQL query for container 'Drafts' in partition 'Sample' [Parameters=[@__get_Item_0='4042662c-3b7a-4970-aee5-8bdc6d5e7d1d']]
      SELECT c
      FROM root c
      WHERE (c["id"] = @__get_Item_0)
      OFFSET 0 LIMIT 1
info: 3/21/2022 14:20:21.259 CosmosEventId.ExecutedReadNext[30102] (Microsoft.EntityFrameworkCore.Database.Command)
      Executed ReadNext (845.2267 ms, 2.79 RU) ActivityId='ec4b24b1-60a2-4ff7-8077-a64854c6f893', Container='Drafts', Partition='Sample', Parameters=[@__get_Item_0='4042662c-3b7a-4970-aee5-8bdc6d5e7d1d']
      SELECT c
      FROM root c
      WHERE (c["id"] = @__get_Item_0)
      OFFSET 0 LIMIT 1

```

### Include provider and version information

EF Core version: 6.0.3
Database provider: Microsoft.EntityFrameworkCore.Cosmos
Target framework:  .NET 6.0
Operating system: Windows 10
IDE: Rider 2021.3.3

**Comment by ggirard07** [comment]
Same issue here... tried to avoid using Guid as Key in favor of string instead in case of conversion issues, no changes.
Also tried to isolates my entity types into distinct container and removed discriminator to get it out of query, still no point read.

**Comment by asos-stefanzilik** [comment]
Is there a workaround?

**Comment by AndriySvyryd** [comment]
The workaround for the original issue is to type the `Id` property as `string`.

**Comment by ChrMaass** [comment]
@koenbeuk Don't want to do a PullRequest for your fix?

**Comment by koenbeuk** [comment]
> @koenbeuk Don't want to do a PullRequest for your fix?

I've abandoned that fix. If I recall correctly, it was only solving part of the problem and creating additional problems. Meanwhile it seems that the issue got resolved by @AndriySvyryd

**Comment by ajcvickers** [comment]
@AndriySvyryd This still doesn't work for me if there are any owned entities in the model. For example, this code:

```C#
var customer = await context.Set<Customer>().FindAsync(customerId);
```

When used with a simple top-level entity:

```C#
public class Customer
{
    public Guid Id { get; set; }
    public required string Name { get; set; }
}
```

Logs a point read:

```
info: 11/2/2023 13:01:09.176 CosmosEventId.ExecutingReadItem[30101] (Microsoft.EntityFrameworkCore.Database.Command) 
      Reading resource 'Customer|c5a074ee-9562-4ccb-affd-08dbdba3c827' item from container 'SomeDbContext' in partition '(null)'.
info: 11/2/2023 13:01:09.196 CosmosEventId.ExecutedReadItem[30103] (Microsoft.EntityFrameworkCore.Database.Command) 
      Executed ReadItem (10 ms, 1 RU) ActivityId='7b9d6e80-7c6b-4412-a3e8-5a4b3ef05215', Container='SomeDbContext', Id='Customer|c5a074ee-9562-4ccb-affd-08dbdba3c827', Partition='(null)'
```

Where-as, if the top-level entity type has an owned type:

```C#
public class Customer
{
    public Guid Id { get; set; }
    public required string Name { get; set; }
    public required Address Address { get; set; }
}
```

Then the same code logs a query:

```
info: 11/2/2023 12:56:25.894 CosmosEventId.ExecutingSqlQuery[30100] (Microsoft.EntityFrameworkCore.Database.Command) 
      Executing SQL query for container 'SomeDbContext' in partition '(null)' [Parameters=[@__get_Item_0='52ac70ad-cfce-4127-5f9e-08dbdba31f44']]
      SELECT c
      FROM root c
      WHERE ((c["Discriminator"] = "Customer") AND (c["Id"] = @__get_Item_0))
      OFFSET 0 LIMIT 1
info: 11/2/2023 12:56:26.088 CosmosEventId.ExecutedReadNext[30102] (Microsoft.EntityFrameworkCore.Database.Command) 
      Executed ReadNext (177.4684 ms, 2.93 RU) ActivityId='a183e9d2-150b-4f73-8127-efee34c9828b', Container='SomeDbContext', Partition='(null)', Parameters=[@__get_Item_0='52ac70ad-cfce-4127-5f9e-08dbdba31f44']
      SELECT c
      FROM root c
      WHERE ((c["Discriminator"] = "Customer") AND (c["Id"] = @__get_Item_0))
      OFFSET 0 LIMIT 1
```

**Comment by alperenbelgic** [comment]
thanks everyone for all contribution. may I ask why this is closed as "not planned"?  I think point read feature is a reasonable expectation even when owned type(s) exists. am I wrong?

**Comment by roji** [comment]
@alperenbelgic this issue was closed as a duplicate of #24202 (see just above); this doesn't mean that the feature won't be implemented, just that there's already another issue tracking it. Please follow that for progress.
