### ISSUE TITLE
Constraint Generation Issue With TPH and multiple relationships

### ISSUE THREAD

**Issue by MH61Aus** [dotnet/efcore#30877]
## Ask a question

I'm playing around with the Blogs and Posts examples, and have crated some entityies using TPH. 

The idea is, there's 2 blog types, Rss Blog and Special Blog. Each customer has one RssBlog and OneSpecialBlog. Each blog, is owned by one customer. 

```
public abstract class Blog
{
    public int BlogId { get; set; }
    public string Url { get; set; }
    public Customer Customer { get; set; }
    public int CustomerId { get; set; } // FK is required here so it knows how to generate one to one relationship
    
    public List<Post> Posts { get; } = new();
}

public class RssBlog : Blog
{
    public string RssUrl { get; set; }
}

public class SpecialBlog : Blog
{
    public int SpecialField { get; set; }
}

public class Customer
{
    public int CustomerId { get; set; }
    public int YearsSubscribed { get; set; }

    //public List<Blog> Blogs { get; set; }

    public SpecialBlog SpecialBlog { get; set; }
    //public List<RssBlog> RssBlogs { get; set; }
    public RssBlog RssBlog { get; set; }
}
```

Note that I've got the CustomerId in Blog. This is because my real datamodel I'm working with (persons and accounts) has this limitation of where the FK is, so I'm constrained to modelling it this way. 

So the problem here is, when it generates the migration, it sees the one to one nature beween SpeicalBlog and Customer, and RssBlog and Customer, and creates a unique index. It is smart enough to only create one index, but its still a problem:

```
            migrationBuilder.CreateIndex(
                name: "IX_Blog_CustomerId",
                table: "Blog",
                column: "CustomerId",
                unique: true);
```

When I do this, I'm going to get an Index violation:

```
db.Customers.Add(new Customer
{
    YearsSubscribed = 20,
    RssBlog = new RssBlog
    {
        Url = "http://rss.blog.com",
        RssUrl = "rss.url",
    },
    SpecialBlog = new SpecialBlog
    {
        Url = "http://special.blog.com",
        SpecialField = 999,
    }
});
db.SaveChanges();
```

because the Index says customerID must be unique in the Blog table. But the uniqueness really should be on customerID + BlogTypeID.

Now, If I take this a step forward and try to achieve the scenario I really want, which is where A customer can own one Special Blog, and multiple RssBlogs:

```
public class Customer
{
    public int CustomerId { get; set; }
    public int YearsSubscribed { get; set; }

    //public List<Blog> Blogs { get; set; }

    public SpecialBlog SpecialBlog { get; set; }
    public List<RssBlog> RssBlogs { get; set; }
    //public RssBlog RssBlog { get; set; }
}
```

When I generate the migration, it creates 2 indexes (one unique, one not) and 2 constraints (a duplicate):

```
        migrationBuilder.CreateIndex(
                name: "IX_Blog_CustomerId",
                table: "Blog",
                column: "CustomerId");

            migrationBuilder.CreateIndex(
                name: "IX_Blog_CustomerId1",
                table: "Blog",
                column: "CustomerId",
                unique: true);

            migrationBuilder.AddForeignKey(
                name: "FK_Blog_Customers_CustomerId",
                table: "Blog",
                column: "CustomerId",
                principalTable: "Customers",
                principalColumn: "CustomerId",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "FK_Blog_Customers_CustomerId1",
                table: "Blog",
                column: "CustomerId",
                principalTable: "Customers",
                principalColumn: "CustomerId",
                onDelete: ReferentialAction.Cascade);
```

Having thr duplicate constraints just gives me a " may cause cycles or multiple cascade paths" error when trying to apply the migraiton.

My way around this is to just hand edit the migration - but my understabnding it that this isn't something I should be doing. But I'm not sure what else to do. Even if I try to build the constraints myself in OnModelCreating, I can't really figure out a way to tell it "you only need one relationship/constraint for these 2 mappings, because of the nature of TPH"

### Include provider and version information

EF Core version: 7.0.5
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: (e.g. .NET 6.0) 7.0
Operating system: Windows 10
IDE: Visual Studio 2022 7.5.4

**Comment by ajcvickers** [comment]
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by MH61Aus** [comment]
@ajcvickers I've pushed the app here: https://github.com/MH61Aus/EFCoreGetStarted

Its a very small console app. Ther'es 2 migrations - the second one being the problematic one. Running Update-Database should blow up with a "may cause cycles or multiple cascade paths" error due to it creating duplicate relationships between the same two columns.

**Comment by ajcvickers** [comment]
@MH61Aus It's still not clear to me what relationships you are trying to create. Are you attempting to use the same FK column for multiple different relationships?

**Comment by MH61Aus** [comment]
@ajcvickers  What my expectation is, is that only one relationship is generated in the database:
FK_Blog_Owners_OwnerId should be created for Blog.OwnerID. 

From what I can see, I could go and add filtered Indexes here which would solved the duplicate generated indexes issue, but wouldn't resolve the duplicate constraint issue.
```
            entity.HasIndex(b => b.OwnerID, "IX_SpecialBlog_Owner")
            .IsUnique()
            .HasFilter($"[Blog_Type] = {(int)BlogTypeEnum.Special}");

            entity.HasIndex(b => b.OwnerID, "IX_RssBlog_Owner")
            .HasFilter($"[Blog_Type] = {(int)BlogTypeEnum.Rss}");
```
If I do this, and manualy delete the duplicate constraint from the migration, everything works as I'd expect it to, and for now its how I'm going to proceeed, but I just didn't think I was supposed to be tweaking the generated migration script.

**Comment by ajcvickers** [comment]
@MH61Aus EF doesn't support this. Each relationship must be represented by a different foreign key.
