### ISSUE TITLE
Nullable object must have a value

### ISSUE THREAD

**Issue by Luigi6821** [dotnet/efcore#30915]
Hi,
I am getting error "Nullable object must have a value" using the following scenario:

var categories = from c in dbContext.Set<AMOS_ADDRESSCATEGORY>().AsNoTracking()
                                 select new
                                 {
                                     Id = c.ADDRESSCATEGORYID,
                                     Name = c.DESCRIPTION
                                 };

var addresses = (from address in dbContext.Set<AMOS_ADDRESS>().AsNoTracking()
                                 join c in categories on address.ADDRESSCATEGORYID equals c.Id into aC
                                 from category in aC.DefaultIfEmpty()
                                 select new
                                 {
                                     Id = address.ADDRESSID,
                                     Category = category
                                 }).ToArray();

The above scenarion works pefectly using EF Standard and works in EF Core if I change to:

var addresses = (from address in dbContext.Set<AMOS_ADDRESS>().AsNoTracking()
                                 **join c in dbContext.Set<AMOS_ADDRESSCATEGORY>().AsNoTracking()** 
                                on address.ADDRESSCATEGORYID equals c.ADDRESSCATEGORYID into aC
                                 from category in aC.DefaultIfEmpty()
                                 select new
                                 {
                                     Id = address.ADDRESSID,
                                     Category = category
                                 }).ToArray();

Can you help me please?
Thanks in advance
Luigi

EF Core version: 8.0.0-preview.4.23259.3
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: NET 6.0
Operating system:
IDE: Visual Studio 2022 17.4

**Comment by ajcvickers** [comment]
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by Luigi6821** [comment]
Hi @ajcvickers 
Please find attached a project for reproducing issue.
 
[ReproducibleNullObject.zip](https://github.com/dotnet/efcore/files/11503022/ReproducibleNullObject.zip)

**Comment by ajcvickers** [comment]
Note for triage: we don't handle assigning null to the anonymous type after calling `DefaultIfEmpty`, but it seems like this should work, and it works in LINQ-to-Objects.

**Comment by Luigi6821** [comment]
Hi @ajcvickers
I believe it has same issue with non anonymous type:
`var categories = from c in dbContext.Set<AMOS_ADDRESSCATEGORY>().AsNoTracking()
                         select new Category
                         {
                             Id = c.ADDRESSCATEGORYID,
                             Name = c.DESCRIPTION
                         };

 var addresses = (from address in dbContext.Set<AMOS_ADDRESS>().AsNoTracking()
                                 join c in categories
                                on address.ADDRESSCATEGORYID equals c.Id into aC
                                 from category in aC.DefaultIfEmpty()
                                 select new
                                 {
                                     Id = address.ADDRESSID,
                                     Category = category
                                 }).ToArray();`

**Comment by Luigi6821** [comment]
Hi, Has been solved in version 8 ?
I tested and seems still present..
Thanks in advance

**Comment by ajcvickers** [comment]
This issue is in the Backlog milestone. This means that it is not fixed in EF Core 8.0. We will [re-assess the backlog](https://docs.microsoft.com/ef/core/what-is-new/release-planning) and consider this item in the upcoming planning. However, keep in mind that there are many other high priority features with which it will be competing for resources. Make sure to vote (👍) for this issue if it is important to you.

**Comment by Luigi6821** [comment]
Hi, thanks for prompt reply. I believe that this issue should be with high priority because fails on a simple left join operation.
Anyway thanks for suggestion

**Comment by UliPlabst** [comment]
I have the same exception using a simple group by statement, I think the root cause might be the same. You can run this in roslyn pad to reproduce.
```cs
#r "nuget: Microsoft.EntityFrameworkCore.Sqlite,8.0.0"
#r "nuget: Microsoft.EntityFrameworkCore,8.0.0"

using System.ComponentModel.DataAnnotations;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

await using var ctx = new Context();
await ctx.Database.EnsureDeletedAsync();
await ctx.Database.EnsureCreatedAsync();

ctx.Steps.Add(new Step
{
    Id = 5
});
await ctx.SaveChangesAsync();

await ctx.Steps
    .GroupBy(e => new
    {
        e.Planned
    }).ToListAsync();

public class Context : DbContext
{
    public DbSet<Step> Steps { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlite(Environment.ExpandEnvironmentVariables("DataSource=%USERPROFILE%/Desktop/test_db.sqlite"))
            .LogTo(Console.WriteLine, LogLevel.Information)
            .EnableSensitiveDataLogging();
}

public class Step
{
    [Key]
    public int Id { get; set; }
    public DateTime? Planned { get; set; }
}

```

**Comment by Luigi6821** [comment]
Hi, 
anu news on the above?
Thanks in advance

**Comment by roji** [comment]
This issue is in the Backlog milestone. This means that it is not planned for the next release (EF Core 8.0). We will [re-assess the backlog](https://docs.microsoft.com/ef/core/what-is-new/release-planning) following the this release and consider this item at that time. However, keep in mind that there are many other high priority features with which it will be competing for resources. Make sure to vote (👍) for this issue if it is important to you.

**Comment by Luigi6821** [comment]
> 

I will "vote" it for sure but let me say that this issue is really a bug for anyone want to outer join tables.

Regards
Luigi

**Comment by adrius** [comment]
We're also experienced the issue on a piece of code very similar to @Luigi6821 , I'll keep an eye on this issue.
Can anybody explain how can we vote this one up?

**Comment by geraparra** [comment]
Same issue here, how can we vote?

**Comment by roji** [comment]
@geraparra vote (thumbs up 👍) in the top comment of the issue.

**Comment by Luigi6821** [comment]
Hi,
I am testing version 9 preview 9.0.0-preview.3.24172.4 and still the error is present.
I am struggled on how this "pillar" functionalities is not working and how any other can use EF core without having it
fixed.

**Comment by roji** [comment]
Yes, this issue is still in the backlog milestone - we haven't yet fixed it. Ultimately, it has only 10 upvotes, meaning that very few users run into it, and therefore it's not at the top of our priority list.

**Comment by Luigi6821** [comment]
> Yes, this issue is still in the backlog milestone - we haven't yet fixed it. Ultimately, it has only 10 upvotes, meaning that very few users run into it, and therefore it's not at the top of our priority list.

I can't believe in users that do not use LEFT outer JOIN. There is some workaround?

**Comment by shaofing** [comment]
This issue has been present since EF Core 5+until now

**Comment by shaofing** [comment]
`
        static void Main(string[] args)
        {
            //Table AppointmentOrder only has 1 record, while table AppointmentDetail has no data.
            var connectionString = $"Data Source=(localdb)\\ProjectModels;Initial Catalog=eftest;Integrated Security=True;Connect Timeout=30;Encrypt=False;Trust Server Certificate=False;Application Intent=ReadWrite;Multi Subnet Failover=False";
            var builder = new DbContextOptionsBuilder<SqliteContext>();
            builder.UseLoggerFactory(LoggerFactory.Create(builder => builder.AddConsole()));
            builder.UseSqlServer(connectionString);
            var dbContext = new SqliteContext(builder.Options);
            var query = from a in dbContext.AppointmentOrder
                         join cc in dbContext.AppointmentDetail on a.AppointmentId equals cc.AppId into ccQuery
                         from c in ccQuery.DefaultIfEmpty()
                         select new
                         {
                             a.AppointmentId,
                             c.DetailCount
                         };
            var list = query.ToList();
            Console.ReadLine();
        }`

**Comment by shaofing** [comment]
I am using `((int?)c.DetailCount).GetValueOrDefault()` instead of it

![image](https://github.com/user-attachments/assets/1d7ca436-8c4c-492f-887e-d50d9a3c7a15)

**Comment by Rookian** [comment]
@roji 
Is there any workaround in the meanwhile, that is not utilizing client-side evaluation?

**Comment by fabiohvp** [comment]
I'll put here because I believe the issue might be the same..

I'm creating a LeftJoin extension method


I'll put here because I believe the issue might be the same..

I'm creating a LeftJoin extension method
```C#
public static class LeftJoinExtension
{
    public static IQueryable<TResult> LeftJoin<TResult, TKey, TLeft, TRight>(
        this IQueryable<TLeft> leftCollection,
        IQueryable<TRight> rightCollection,
        Expression<Func<TLeft, TKey>> leftExpression,
        Expression<Func<TRight, TKey>> rightExpression,
        Expression<Func<TLeft, TRight, TResult>> resultSelector
    )
    {
        var query = (
            from l in leftCollection
            join r in rightCollection
                on leftExpression.Invoke(l)
                equals rightExpression.Invoke(r)
                into rJoin
            from r in rJoin.DefaultIfEmpty()
            select resultSelector.Invoke(l, r)
        )
        .AsExpandableEFCore();
        return query;
    }
}

public record Projection(ClassA Left, ClassB Right);

var query = source1
    .LeftJoin(
        source2
        o => new { o.Id },
        c => new { c.Id },
        (o, c) => new Projection(o, c) //this doesn't work
        //(o, c) => new { Opportunity = o, Currency = c } //this works
    );

var result = query
   .Where(o => o.Right != null) //exception will happen when I have this line
   .Select(o => new TestProjection(
       o.Right == null ? null : o.Right.ColumnA,
       o.Left.ColumnA
   ))
   .Take(25)
   .ToList();
```


this is the exception:
```C#
System.InvalidOperationException: 'The LINQ expression 'DbSet<ClassA>()
    .LeftJoin(
        inner: DbSet<ClassB>(), 
        outerKeySelector: f => new { 
            Id = f.Id
         }, 
        innerKeySelector: c => new { 
            Id = c.Id
         }, 
        resultSelector: (f, c) => new TransparentIdentifier<ClassA, ClassB>(
            Outer = f, 
            Inner = c
        ))
    .Where(ti => new Projection(
        ti.Outer, 
        ti.Inner
    ).Right != null)' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to 'AsEnumerable', 'AsAsyncEnumerable', 'ToList', or 'ToListAsync'. See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.'
```

**Comment by theloserbm** [comment]
Hi all, today we had a similar issue but managed to workaround it by assigning the values directly into the select class.

```
var categories = from c in dbContext.Set<AMOS_ADDRESSCATEGORY>().AsNoTracking()
                                 select new
                                 {
                                     Id = c.ADDRESSCATEGORYID,
                                     Name = c.DESCRIPTION
                                 };

var addresses = (from address in dbContext.Set<AMOS_ADDRESS>().AsNoTracking()
                                 join c in categories on address.ADDRESSCATEGORYID equals c.Id into aC
                                 from category in aC.DefaultIfEmpty()
                                 select new
                                 {
                                     Id = address.ADDRESSID,
                                     //Category = category
                                     CategoryId = category != null ? category.Id : null,
                                     CategoryName = category != null ? category.Name : null
                                 }).ToArray();
```

Hopefully can help someone with this.

**Comment by mwerberacs** [comment]
any update on this? i was hoping it would be fixed with the introduction of an official LeftJoin implementation, but it's still an issue, and it's causing me significant frustration.

.zip file of a program i spun up to test what works and what doesn't:
[LeftJoinNullableRepro.zip](https://github.com/user-attachments/files/23371608/LeftJoinNullableRepro.zip)

everything works as expected when working with the base entities. the bug only happens when dealing with DTOs or anonymous types. the error is thrown because the query creates objects of those types in their "default" state rather than returning null.

doing FirstOrDefault() instead works fine, but that's only good if 1) you know it's a many/one-to-one relationship, and 2) the query doesn't contain multiple GroupJoins (since EFCore still can't translate more than one GroupJoin).

**Comment by roji** [comment]
No update yet, this is in the backlog.

**Comment by roji** [comment]
Also see #38055 when working on this.

**Comment by ajcvickers** [comment]
Remaining work following fix in #38479:

- [ ] Second join applied after the left join, then whole-object projection (shaper rebuilt → marker lost). Repro: closed dup #26873.
- [ ] `GroupBy` applied after the left join, then whole-object projection (shaper rebuilt via `ApplyGrouping`). Repro: closed dup #28119.
- [ ] Plain inner with no pushdown (no aggregate/filter) via the `LeftJoin` operator — marker is inlined into the combined `SELECT` and never becomes `NULL`. *(no dedicated issue)*
- [ ] Value-type `struct` / `record struct` whole-object projection (members not defaulted; materialization throws).
- [ ] Constructor-bound DTO / positional `record struct` / `ValueTuple` whole-object projection (fails at translation — a distinct path). Overlaps #28248.
- [x] `Union` / set-operation of two left-join non-entity projections (set-operation translation failure). *(no dedicated issue)*
- [ ] Server-side `obj == null` / `obj != null` on a left-joined non-entity, in `Where` / `OrderBy` (translation failure). A complete #22517 (true null-tracking) would likely enable this. *(no dedicated issue)*
- [ ] `RightJoin` where the **outer** (non-entity) side is the nullable one — the marker is injected for the inner side only, so this still throws.
- [ ] `Nullable<T>` whole-object projection (latent and currently unreachable; the gate skips on `IsValueType`, but `default(T?)` is `null`).
- [ ] InMemory provider parity — same gap in `InMemoryQueryExpression.AddJoin` (this PR is relational-only). Related InMemory case #23425 was closed `NOT_PLANNED`.
