### ISSUE TITLE
Question: reduce memory usage as much as possible

### ISSUE THREAD

**Issue by JanEggers** [dotnet/efcore#31337]
im trying to reduce the allocations in the hot path of our rest api. by basically manually json formatting the result as part of the linq i was able to avoid the allocation of the model object. currently experimenting with EF7. my result set is 10K rows.

When looking at the allocation performance profiler there seem to be some allocations because of async locals used by ef. but i found a way around that by disabling the concurrency check. (  .EnableThreadSafetyChecks(false))

what remains are the formatted strings and the values that are formatted into the string.

![image](https://github.com/dotnet/efcore/assets/6747376/53ecc272-64f0-4c60-817d-89d956182429)

Is there any way to translate the string.format call to sql so I get back just the actual result I want without the need to execute string.format on the client? I also tried to use string interpolation but that seems to use an additional object array.

### Include your code

```C#
var companiesAsJson = _context.Companies.Take(take).AsNoTracking()
        .Select(c => string.Format("{{\"Id\": {0}, \"Name\": \"{1}\"  }}", c.Id, c.Name));

var writer = Response.BodyWriter;
      var encoding = Encoding.UTF8;

      writer.Write(encoding.GetBytes("["));

      foreach (var company in companiesAsJson)
      {
          encoding.GetBytes(company, writer);
      }
      writer.Write(encoding.GetBytes("]"));

      await writer.FlushAsync();
```

**Comment by roji** [comment]
@JanEggers yes, you should be able to use the string concatenation operator instead (e.g. `.Select(c => "Id: " + c.Id + " Name: " + c.Name)`).

I'm curious if you're seeing an actual performance difference by eliminating these allocations (this also includes EnableThreadSafetyChecks). I appreciate general attempts to e.g. get allocations down to zero, but in almost all real-world applications these shouldn't have any actual impact on the app's end throughput.

**Comment by JanEggers** [comment]
with my current approach the api response time drops from 40ms to 20ms so i call that real gains. I will try your suggestion

**Comment by JanEggers** [comment]
looking better :)

![image](https://github.com/dotnet/efcore/assets/6747376/0bc7d48e-af99-4156-b794-708539bdd456)

i suppose ony you guys can fix the char[] allocation in tdsparser?!

**Comment by roji** [comment]
> with my current approach the api response time drops from 40ms to 20ms so i call that real gains.

I'd be very surprised if something like EnableThreadSafetyChecks() or the transition from client-side string.Format to server-side string concatenation resulted in such a huge change; it's very likely that some other unrelated change you did is responsible for that. Mind you, I'm not trying to argue against performance optimizations, just to be very clear on which change produces which kind of gain, in order to save you a lot of micro-optimization work that won't affect your end-to-end perf in any way.

**Comment by roji** [comment]
> i suppose ony you guys can fix the char[] allocation in tdsparser?

You can try asking on the [SqlClient repo](https://github.com/dotnet/sqlclient), though I suspect that allocation may be necessary for it to do its work.

I'm going to go ahead and close this as there's no additional outstanding question, but feel free to post back with more info or questions.

**Comment by JanEggers** [comment]
issue in sql client was already fixed just had to update :)

https://github.com/dotnet/SqlClient/pull/1866

**Comment by Havunen** [comment]
The issue is not fixed yet, but its slightly better:
https://github.com/dotnet/SqlClient/issues/2120
