### ISSUE TITLE
Question: Migrate existing Data in Json Columns the right way with EF8 Core

### ISSUE THREAD

**Issue by iqmeta** [dotnet/efcore#32301]
Hi there, 
looking for an example on:

**How to update/change with migration the exitsing data in the JsonColumns so I don't run into not exsiting paths exception?**

Just saw dotnefconf 2023... great job, instantly playing a bit around how it behaves with model changes over dev/app lifetime.

Creation worked fine...

```
public class BlogLinks
{
    public string? Url { get; set; }
    public string? Text { get; set; }
}
```
![image](https://github.com/dotnet/efcore/assets/7533842/85679c51-e00f-4af1-a4bd-f67935b0fd22)

After model change

```
public class BlogLinks
{
    public string? Url { get; set; }
    public string? Text { get; set; }
    public string? SomeThingNew { get; set; }
}
```
the `dotnet ef database update` was successful but did not any change to the data JSON in the JSON Columns,
like adding the new Property of Model eg `{ SomeThingNew : null } `

So although the model in C# knows the property `SomeThingNew `
adding some info throws "**Property cannot be found on the specified JSON path**"

![image](https://github.com/dotnet/efcore/assets/7533842/0f880b7a-a6b0-4660-acc5-dbc27a378279)

Adding new one is no problem:

![image](https://github.com/dotnet/efcore/assets/7533842/be836e5e-7bc6-4739-928e-639d2d677dbf)

So it's just how is the EF8 Core way of doing this migration update on existing models in json data right.

Cheers Otto.

**Comment by ajcvickers** [comment]
Notes from triage: as it stands, there isn't a great way to evolve the document model and yet still load older documents. However, we could store the model history of the document and use that to automatically update older docs to the latest version.

**Comment by robi26** [comment]
I'm having the exact same problem. 
Would be nice if the properties are populated with their default values if the do not exist in the JSON.

**Comment by VaclavElias** [comment]
I also voted for this issue now. I also came across this error `Property cannot be found on the specified JSON path`. 

Also using similar approach as here https://github.com/dotnet/efcore/issues/32642, I was assuming, I can add more settings and that EF will handle this automatically.

Reversing back to this:

```csharp
//options.OwnsOne(p => p.Settings).ToJson();

 options.Property(e => e.Settings).HasConversion(
      v => JsonSerializer.Serialize(v, new JsonSerializerOptions
      {
           DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull
      }),
      v => JsonSerializer.Deserialize<ApplicationUserSettings>(v, new JsonSerializerOptions
     {
            DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull
     }));
```

**Comment by roji** [comment]
@VaclavElias this issue shouldn't be a reason to revert from ToJson() to using value converters - evolving the document model isn't supported in either case.

**Comment by VaclavElias** [comment]
Well, maybe it isn't. But it didn't throw the error and saved my data to the table 🙂. Maybe it is slightly different that's why it worked?

**Comment by samba2** [comment]
Stumbled across the same issue. Saw the dotnetconf 23 demo (@roji great demo, nice mix of explaination and hands-on 👍🏽) and gave [the demo code](https://github.com/ajcvickers/DotNetConf2023/) a local spin. As Martin Kleppmann once wrote: There is always a schema, either explicit (as with classic DB schema) or implicit where you check the state of your value in the code (e.g. null check).
So my expectation was, that, whatever property I add will be filled with null by default so that my client code needs to deal with that.

To try that out I added a new "Description" field to [the "Phone" entity](https://github.com/ajcvickers/DotNetConf2023/blob/main/CustomersApp/EntityTypes.cs#L27):
````csharp
public class Phone
{
    public required int CountryCode { get; set; }
    public required string Number { get; set; }
    public bool IsPrimary { get; set; }
    public required string Description { get; set; }    // new
}
````

My "give me all phone numbers" LINQ query:
````csharp
await using (var context = new CustomersContext())
{
    var phoneNumbers = await context.Set<Customer>()
        .AsNoTracking() // fixes "JSON entity or collection can't be projected directly in a tracked query" 
        .SelectMany(c => c.Details.PhoneNumbers)
        .ToListAsync();
}
````

Console output:
````
info: 24.03.2024 21:04:35.085 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command) 
      Executed DbCommand (31ms) [Parameters=[], CommandType='Text', CommandTimeout='30']                                
      SELECT [c].[Id], [p].[CountryCode], [p].[Description], [p].[IsPrimary], [p].[Number]                              
      FROM [Customers] AS [c]                                                             
      CROSS APPLY OPENJSON([c].[Details], '$.PhoneNumbers') WITH (                        
          [CountryCode] int '$.CountryCode',                                              
          [Description] nvarchar(max) '$.Description',                                    
          [IsPrimary] bit '$.IsPrimary',                                                  
          [Number] nvarchar(max) '$.Number'                                               
      ) AS [p]                                                                            
fail: 24.03.2024 21:04:35.139 CoreEventId.QueryIterationFailed[10100] (Microsoft.EntityFrameworkCore.Query) 
      An exception occurred while iterating over the results of a query for context type 'CustomersContext'.
      System.Data.SqlTypes.SqlNullValueException: Data is Null. This method or property cannot be called on Null values.
         at Microsoft.Data.SqlClient.SqlBuffer.ThrowIfNull()
         at Microsoft.Data.SqlClient.SqlBuffer.get_String()
         at Microsoft.Data.SqlClient.SqlDataReader.GetString(Int32 i)
         at lambda_method3(Closure, QueryContext, DbDataReader, ResultContext, SingleQueryResultCoordinator)
         at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
Unhandled exception. System.Data.SqlTypes.SqlNullValueException: Data is Null. This method or property cannot be called on Null values.
   at Microsoft.Data.SqlClient.SqlBuffer.ThrowIfNull()
   at Microsoft.Data.SqlClient.SqlBuffer.get_String()
   at Microsoft.Data.SqlClient.SqlDataReader.GetString(Int32 i)
   at lambda_method3(Closure, QueryContext, DbDataReader, ResultContext, SingleQueryResultCoordinator)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Program.<Main>$(String[] args) in C:\work\Projects\EfCore8Example\CustomersApp\Program.cs:line 30
   at Program.<Main>$(String[] args) in C:\work\Projects\EfCore8Example\CustomersApp\Program.cs:line 34
   at Program.<Main>(String[] args)
````

Tbh. now I am unsure if I should use EFCore 8 for my purpose (storing nested documents in MSSQL) as I always will have new properties coming in. A clear way for "how to do schema evolution for a JSON document" is crucial.

**Comment by redapollos** [comment]
Agreed with the above, this feature is not usable if the structure can't easily be updated.

**Comment by roji** [comment]
@samba2 @redapollos there's no issue with adding a new property to an existing model - the problem is trying to add a **non-nullable** one; this is in fact quite similar to the problem of adding a non-JSON, regular relational column to an existing table when that column is non-nullable - what should happen to the existing rows?

One way to deal with this is to add a nullable column, and then deal with null values in your application. Another is to perform an UPDATE to create the JSON property for all existing rows with some default value of your choice (this can be done by [integrating SQL in your migrations](https://learn.microsoft.com/en-us/ef/core/managing-schemas/migrations/managing?tabs=dotnet-core-cli#adding-raw-sql)). We do have plans to make this easier (e.g. by possibly having EF automatically do the UPDATE for you based on a default value you configure on the property), but I wouldn't consider this a blocker, or the feature to currently be "not usable" because of this.

**Comment by samba2** [comment]
@roji thank you for your response. I will try out your suggestions as soon as I find a minute 👍🏽. I think adding a note to the EF Core docs with your hints is probably just enough for now. As someone not growing up with EF Core any piece of guidance is useful and usual your docs are very helpful in that regard (this was a compliment 😉)

**Comment by benagain** [comment]
> @samba2 @redapollos there's no issue with adding a new property to an existing model - the problem is trying to add a **non-nullable** one

Hi @roji, I thought the problem *was* with adding a nullable property to an existing model?   @iqmeta's original report adds a nullable property, and that's certainly the problem I've encountered.  I created a tiny project to demonstrate - [benagain/SqlJsonMigration](https://github.com/benagain/SqlJsonMigration).

Maybe I've missed something obvious?

**Comment by roji** [comment]
@benagain my comments were for @samba2, whose [comment](https://github.com/dotnet/efcore/issues/32301#issuecomment-2016930389) above shows them trying to add a non-nullable property.

And more in general, my point was to make clear that users can add an UPDATE to patch the JSON documents themselves into the migrations, which isn't a perfect situation, but a pretty good workaround. Other than that, AFAIK apart from some edge cases, adding a nullable property works pretty well.

**Comment by roji** [comment]
@benagain can you put together a minimal, runnable console program that shows the problem? This may very well be a different issue from the above.

**Comment by benagain** [comment]
@roji, of course :) that's what https://github.com/benagain/SqlJsonMigration is - I create a model and migration; run the program to insert a row; add a nullable property to the model and migrate the db, then attempt to update the existing row.

**Comment by iqmeta** [comment]
> @roji, of course :) that's what https://github.com/benagain/SqlJsonMigration is - I create a model and migration; run the program to insert a row; add a nullable property to the model and migrate the db, then attempt to update the existing row.

example looks to me also like something of a minimal version / app in real world usage...

next thing..  when ef core is not dumping on nullable anymore... will json document gets updated when a value is assigned an saved - json document gets updated according to model ;-)

**Comment by samba2** [comment]
Thanks @iqmeta for providing the example. I've played a bit with updating nullable properties where the old JSON does not contain the property to update.

This code...
````csharp
var existing = await context.Documents.ToListAsync();
...
existing.First().Json.NewProperty = "world";
````

...leads to this UPDATE:
````SQL
UPDATE [Documents] SET [Json] = JSON_MODIFY([Json], 'strict $.NewProperty', @p0)
OUTPUT 1
WHERE [Id] = @p1;
``````
which gives the mentioned error: `Microsoft.Data.SqlClient.SqlException (0x80131904): Property cannot be found on the specified JSON path.`

The problem seems to be the `strict` keyword: 
_strict - Specifies that the property referenced by <json path> must be in the JSON expression. If the property is not present, JSON_MODIFY returns an error._ [link](https://learn.microsoft.com/en-us/sql/t-sql/functions/json-modify-transact-sql?view=sql-server-ver16#arguments)

I wrote this piece of code to work around that, key change being the missing `strict` keyword which defaults to `lax`: _If the property is not present, JSON_MODIFY tries to insert the new value on the specified path._
`````csharp
var myDocument = existing.First();
if (myDocument.Json.NewProperty == null)
{
    Console.WriteLine($"Update existing document via SQL");
    context.Database.ExecuteSql(
        $"update Documents set Json = JSON_MODIFY(Json, '$.NewProperty', 'world') where Id = {myDocument.Id}");
}
`````
Here the update went smoothly. 

@roji Is there a way to ask EF Core to not use `strict` in the "non-existing property" cases ?

**Comment by Marcel0024** [comment]
I just hit this myself. I'm surprised more people haven't run into this. 

@samba2 

Looking at the code here: https://github.com/dotnet/efcore/blob/34b34b98e9ebf367bf2e212289c6b7fec9742521/src/EFCore.SqlServer/Update/Internal/SqlServerUpdateSqlGenerator.cs#L151

There doesn't seem to be any way to override this.

**Comment by jmrtnz94** [comment]
I've been encountering this error over the past week. I initially commented on this issue [here](https://github.com/dotnet/efcore/issues/33565#issuecomment-2155524697).

My JSON column stores an array of bullet points. Initially, my entity had only one property, "Text." Recently, I added an "Order" property and ran a process to backfill this order. Interestingly, certain entities encountered the error `Microsoft.Data.SqlClient.SqlException (0x80131904): Property cannot be found on the specified JSON path`, while others saved to the database successfully.

I finally identified the reason for these failures. In my scenario, if the "Order" property was the only change on the entity, EF Core would use JSON_MODIFY() with strict mode to update the database, causing the error. This occurred when my entity had only one bullet point and the "Order" property was the sole change in my JSON column. Conversely, when both the "Text" and "Order" properties were updated, or when there were multiple bullet points with the "Order" property added/updated, EF Core did not use JSON_MODIFY and the entities saved without issues.

SQL Generated when json column only had a single "Order" property changed
```sql
SET IMPLICIT_TRANSACTIONS OFF;
SET NOCOUNT ON;
UPDATE [Table] SET [Bullets] = JSON_MODIFY([Bullets], 'strict $[0].Order', @p0)
OUTPUT INSERTED.[ValidFrom], INSERTED.[ValidTo]
```

SQL Generated when json column had multiple changes.
```sql
SET IMPLICIT_TRANSACTIONS OFF;
SET NOCOUNT ON;
UPDATE [Table] SET [Bullets] = @p0,
OUTPUT INSERTED.[ValidFrom], INSERTED.[ValidTo]
```

**Comment by Lindsay-Mathieson** [comment]
> Agreed with the above, this feature is not usable if the structure can't easily be updated.

Agree, I thought the whole point of json columns was their flexibility, this removes that altogether.

**Comment by Lindsay-Mathieson** [comment]
I wrote a command interceptor to change 'strict' to 'lax', which resolved the issue for me, but maybe my approach is naive? Worried that long term I'm creating issues

```c#
public class JSONCommandInterceptor : DbCommandInterceptor
{
    public override InterceptionResult<DbDataReader> ReaderExecuting(DbCommand command, CommandEventData eventData, InterceptionResult<DbDataReader> result)
    {
        RemoveJSONStrictCommand(command);
        return base.ReaderExecuting(command, eventData, result);
    }

    public override ValueTask<InterceptionResult<DbDataReader>> ReaderExecutingAsync(DbCommand command, CommandEventData eventData, InterceptionResult<DbDataReader> result, CancellationToken cancellationToken = default)
    {
        RemoveJSONStrictCommand(command);
        return base.ReaderExecutingAsync(command, eventData, result, cancellationToken);
    }

    private static void RemoveJSONStrictCommand(DbCommand command)
    {
        if (command.CommandText.Contains("'strict $."))
            command.CommandText = command.CommandText.Replace("'strict $.", "'lax $.");
    }
}

```

**Comment by roji** [comment]
See https://github.com/dotnet/efcore/issues/21006 for having a default value when reading missing properties (in Cosmos, but the same should hold for relational), specifically for the (very common) scenario of adding a new property with existing documents.

**Comment by samba2** [comment]
Thanks for the tip!

Shay Rojansky ***@***.***> schrieb am Fr., 28. Feb. 2025,
20:15:

**Comment by josephpdowney** [comment]
Having the same issue, anything happening with this? Any work arounds?

**Comment by roji** [comment]
This issue is in the Backlog milestone. This means that it is not planned for the next release (EF Core 10.0). We will [re-assess the backlog](https://docs.microsoft.com/ef/core/what-is-new/release-planning) following the this release and consider this item at that time. However, keep in mind that there are many other high priority features with which it will be competing for resources. Make sure to vote (👍) for this issue if it is important to you.

**Comment by jstrugnell** [comment]
It seems a fix for this still isn't being planned. What is the workaround for now? To be honest I don't understand why this isn't a bigger issue. Luckily I haven't had to modify the JSON-based aspects of my schema since building an app a couple of years ago. When the client asked for a few new fields, I thought "no problem", just add them as nullable fields and we'd be good to go. Nope. Adding the first of those new fields meant I hit the "Property cannot be found on the specified JSON path" exception.

After trying various hacks to workaround this, I realised that someone above mentioned the issue didn't occur if you updated more than one field. They were right. Luckily I had 3 fields to add so I added all 3, and was then able to update the database. I'm hoping that will suffice for now, but it feels brittle (for instance if a user only updates one of those fields before saving).

I did look at running SQL scripts to update existing records to include the new fields (set to null) but SQL Server (at least the version I'm using - 2019) wouldn't let me set a JSON value to null (it would remove the whole field instead). So it was looking like needing to use string manipulation, which seems ridiculous. 

What am I missing? There must be a way to add new fields to a JSON based column? Or is it just that I'm running old EF Core (V8) and old SQL Server?

**Comment by roji** [comment]
> Luckily I haven't had to modify the JSON-based aspects of my schema since building an app a couple of years ago. When the client asked for a few new fields, I thought "no problem", just add them as nullable fields and we'd be good to go. Nope. Adding the first of those new fields meant I hit the "Property cannot be found on the specified JSON path" exception.

This has already been fixed in EF 9.0 (#21006) - you'll need to upgrade. If you're encountering an issue around this with EF 9.0 or above, please open a new issue with a minimal and we'll investigate. This issue here (#32301) tracks a far greater scope of model evolution than simply adding a property.

**Comment by jstrugnell** [comment]
> > Luckily I haven't had to modify the JSON-based aspects of my schema since building an app a couple of years ago. When the client asked for a few new fields, I thought "no problem", just add them as nullable fields and we'd be good to go. Nope. Adding the first of those new fields meant I hit the "Property cannot be found on the specified JSON path" exception.
> 
> This has already been fixed in EF 9.0 ([#21006](https://github.com/dotnet/efcore/issues/21006)) - you'll need to upgrade. If you're encountering an issue around this with EF 9.0 or above, please open a new issue with a minimal and we'll investigate. This issue here ([#32301](https://github.com/dotnet/efcore/issues/32301)) tracks a far greater scope of model evolution than simply adding a property.

Ah ok, thank you. I will set up a blank app and try that out. That other issue you linked to seems to reference non-nullable properties though? My properties are nullable, but I'll give it a go. Thanks.

**Comment by jstrugnell** [comment]
Unfortunately I still get the same issue in .Net 9.0 + EF 9. 😩 I'm not sure I should open a new issue. This one seems to cover it. There is even a repro already set up by @benagain here - https://github.com/benagain/SqlJsonMigration

I can upload another sample if necessary? 

The crux of this issue from my perspective, is this comment - https://github.com/dotnet/efcore/issues/32301#issuecomment-2160810509. Different SQL is generated if only one value is modified, as compared to if multiple fields are modified. If I only modify the new property, the SQL generated isn't capable of setting the value in the JSON, if the property doesn't already exist in the JSON (set to NULL).

So the SQL can update the NewProperty value in this JSON - {"id": 1, "Color": "Red", "NewProperty": null}
But it can't add/update it if it doesn't exist, like this - {"id": 1, "Color": "Red"}

And I've not been able to find a SQL command (for SQL Server 2019) that will safely add a new JSON property to an existing record and set it to null, as it always removes the whole property, rather than including it but setting it to equal null.
