### ISSUE TITLE
EFCore 9.0 does not respect [Required] on [Owned] properties.

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/efcore#35669]
### Bug description

In EFCORE9.0, owned entities with [Required] string value are not properly notated as NOT NULL.
This worked correctly in EFCORE6.0 but broke on upgrade to EFCORE9.0.
This issue has just now come to light because we've been having performance problems with instances of our application that were created post-EFCore6.

In EFCore 6.0, the attached code generates the following SQL table:

```
CREATE TABLE [dbo].[Users](
	[Id] [nvarchar](450) NOT NULL,
	[Original_FirstName] [nvarchar](max) NOT NULL,
	[Final_FirstName] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_Users] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
```

Specifically, notice that the Final_FirstName and Final_LastName are ```NOT NULL```.

However, in EFCORE7 and above, the following SQL is generated:
```
CREATE TABLE [dbo].[Users](
	[Id] [nvarchar](450) NOT NULL,
	[Original_FirstName] [nvarchar](max) NULL,
	[Final_FirstName] [nvarchar](max) NULL,
 CONSTRAINT [PK_Users] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
```

### Your code

```csharp
using Microsoft.EntityFrameworkCore;
using System.Reflection.Metadata;

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Design;
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;


namespace ConsoleApp20
{
    internal class Program
    {
        static async Task Main(string[] args)
        {
            var DB = new MyContext();
            await DB.Database.EnsureDeletedAsync();
            await DB.Database.EnsureCratedAsync();

        }
    }

    public class MyContext : DbContext {

        // The following configures EF to create a Sqlite database file in the
        // special "local" folder for your platform.
        protected override void OnConfiguring(DbContextOptionsBuilder options) {
            options.UseSqlServer("Integrated Security=SSPI;Server=(local);TrustServerCertificate=True;Database=____TEST_DB;");

        }

        protected override void OnModelCreating(ModelBuilder modelBuilder) {
            base.OnModelCreating(modelBuilder);

            modelBuilder.Entity<Frame<UserPacket>>()
                .ToTable("Users")
                ;

        }

    }

    public class Frame {
        [Required]
        public string Id { get; set; } = string.Empty;
    }

    public class Frame<T> : Frame where T :new() {
        public T Original { get; set; } = new();
        public T Final { get; set; } = new();
    }

    [Owned]
    public class Packet {

    }

    public class UserPacket : Packet {
        [Required]
        public string FirstName { get; set; } = string.Empty;
    }



}
```

### Stack traces

```text

```

### Verbose output

```text

```

### EF Core version

9.0.2

### Database provider

Microsoft.EntityFrameworkCore.SqlServer

### Target framework

.NET 9.0

### Operating system

Windows 11

### IDE

VS 2022

**Comment by roji** [comment]
@TonyValenti as always, we need a minimal, runnable repro (console program) - a bunch of partial snippets is rarely enough for us to reproduce the problem. See below for an attempted minimal repro with EF 9.0.

<details>
<summary>Attempted repro</summary>

```c#
await using var context = new BlogContext();
await context.Database.EnsureDeletedAsync();
await context.Database.EnsureCreatedAsync();

public class BlogContext : DbContext
{
    public DbSet<Blog> Blogs { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlServer("Server=localhost;Database=test;User=SA;Password=Abcd5678;Connect Timeout=60;ConnectRetryCount=0;Encrypt=false")
            .LogTo(Console.WriteLine, LogLevel.Information)
            .EnableSensitiveDataLogging();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Blog>().OwnsOne(b => b.Owned);
    }
}

public class Blog
{
    public int Id { get; set; }
    public string Name { get; set; }

    public Owned Owned { get; set; }
}

public class Owned
{
    [Required] public string FirstName { get; set; } = string.Empty;
}
```

SQL:

```sql
CREATE TABLE [Blogs] (
    [Id] int NOT NULL IDENTITY,
    [Name] nvarchar(max) NOT NULL,
    [Owned_FirstName] nvarchar(max) NOT NULL, -- Note NOT NULL, as expected
    CONSTRAINT [PK_Blogs] PRIMARY KEY ([Id])
);
```

</details>

**Comment by TonyValenti** [comment]
@roji - The code you posted does not reproduce the issue.  The code I posted does.
I'll try to trim mine up more though.

**Comment by TonyValenti** [comment]
@roji - I just updated my code with a minimal example.  This appears to be related to generics.

**Comment by roji** [comment]
@TonyValenti running your code exactly as-is yields the following SQL for me:

```sql
CREATE TABLE [Blogs] (
    [Id] nvarchar(450) NOT NULL,
    [Owned_Value] nvarchar(max) NOT NULL, -- Note NOT NULL
    CONSTRAINT [PK_Blogs] PRIMARY KEY ([Id])
);
```

So this still doesn't repro (with EF 9.0.2).

**Comment by TonyValenti** [comment]
Hi @roji - 
I have two snippets of code above: one that triggers the bug and one that doesn't.  You ran the wrong one.  :-)

Run this code and it will trigger the bug:
```
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using Microsoft.Extensions.Logging;

await using var context = new BlogContext();
await context.Database.EnsureDeletedAsync();
await context.Database.EnsureCreatedAsync();

public class BlogContext : DbContext {
    public DbSet<Blog<UserPacket>> Blogs { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlServer("Integrated Security=SSPI;Server=(local);TrustServerCertificate=True;Database=____TEST_DB;")
            .LogTo(Console.WriteLine, LogLevel.Information)
            .EnableSensitiveDataLogging();

}


public class Blog<T> where T : new() {
    [Required]
    public string Id { get; set; } = string.Empty;

    //This member's [Required] values are NOT properly recorded.
    public T Owned { get; set; } = new();

}

[Owned]
public class UserPacket {
    [Required]
    public string Value { get; set; } = string.Empty;
}

```

**Comment by TonyValenti** [comment]
Hi @AndriySvyryd - I hate to bug you but this is really high priority for us.  Any chance you could take a look?  Thanks so much.

**Comment by AndriySvyryd** [comment]
@TonyValenti As a workaround, you can mark the owned navigations as required:

```C#
    public class Blog<T> where T : new()
    {
        [Required]
        public string Id { get; set; } = string.Empty;

        [Required]
        public T Owned { get; set; } = new();
    }
```

**Comment by AndriySvyryd** [comment]
@roji `NullabilityInfo` for `Owned` returns nullable, is this a known limitation?

**Comment by roji** [comment]
@AndriySvyryd IIRC the representation of the nullability attributes may be slightly different around generic types - that's likely the source of this. If so, it shouldn't be hard to fix (or repro, if there's an issue in NullabilityInfo) if you or someone else in the team wants to investigate.

**Comment by roji** [comment]
Finally looked into this, and it indeed seems to be an issue with NullabilityInfoContext; see https://github.com/dotnet/runtime/issues/117068#issuecomment-3364824243. The workaround for now is to not rely on nullable reference types to configure something as required, but use EF methods as @AndriySvyryd suggested above.

**Comment by TonyValenti** [comment]
I saw that this had the bug tag removed.

Do you have an ETA on when this fix will be in place?

**Comment by roji** [comment]
@TonyValenti see my message just above, this is not an issue in EF - at least not until the runtime people confirm what's going on.
