### ISSUE TITLE
RC1 dnxcore50 Could not load file or assembly System.Data.SqlClient

### ISSUE THREAD

**Issue by hahmed** [dotnet/efcore#3637]
**Due to an issue in DNX dependency resolution, the following error may be encountered when running on dnxcore50.**

> System.IO.FileNotFoundException: Could not load file or assembly 'System.Data.SqlClient, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

**This is a confirmed issue in DNX and a fix is underway.**

<hr />

**Outdated Details**

The following details were from the original bug report on Beta 8 which was expected because it was attempting to use SQL Client on OSX. The issue is now showing up on RC1 on Windows (keeping the original details though).

My packages are:

```
  "dependencies": {
    "Microsoft.AspNet.Diagnostics": "1.0.0-beta8",
    "Microsoft.AspNet.Mvc": "6.0.0-beta8",
    "Microsoft.AspNet.Mvc.TagHelpers": "6.0.0-beta8",
    "Microsoft.AspNet.Server.Kestrel": "1.0.0-beta8",
    "Microsoft.AspNet.StaticFiles": "1.0.0-beta8",
    "Microsoft.AspNet.Tooling.Razor": "1.0.0-beta8",
    "Microsoft.Framework.Configuration.Json": "1.0.0-beta8",
    "Microsoft.Framework.Logging": "1.0.0-beta8",
    "Microsoft.Framework.Logging.Debug": "1.0.0-beta8",
    "Microsoft.Framework.Logging.Console": "1.0.0-beta8",
    "Microsoft.AspNet.Authentication.Cookies": "1.0.0-beta8",
    "Microsoft.Net.Http.Client": "1.0.0-beta8",
    "EntityFramework.SqlServer": "7.0.0-beta8",
    "EntityFramework.Commands": "7.0.0-beta8",
    "Microsoft.Dnx.Runtime.Abstractions": "1.0.0-beta8",
    "Microsoft.AspNet.Identity": "3.0.0-beta8",
    "Microsoft.AspNet.Identity.EntityFramework": "3.0.0-beta8",
    "Microsoft.AspNet.Authorization": "1.0.0-beta8"
  },
```

The error I am getting is:

```
error   : [Microsoft.Data.Entity.Query.QueryCompilationContext] An exception occurred in the database while iterating the results of a query.
System.IO.FileNotFoundException: Could not load file or assembly 'System.Data.SqlClient, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

File name: 'System.Data.SqlClient, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' ---> System.IO.FileNotFoundException: Could not load the specified file.
File name: 'System.Data.SqlClient'
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyName(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.Resolve(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)
   at Microsoft.Data.Entity.Storage.Internal.SqlServerConnection.CreateDbConnection()
   at Microsoft.Data.Entity.Internal.LazyRef`1.get_Value()
   at Microsoft.Data.Entity.Storage.RelationalConnection.Open()
   at Microsoft.Data.Entity.Query.Internal.QueryingEnumerable.Enumerator.MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__20`2.MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source)
   at lambda_method(Closure )
   at Microsoft.Data.Entity.Query.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
error   : [Microsoft.AspNet.Diagnostics.DeveloperExceptionPageMiddleware] An unhandled exception has occurred while executing the request
System.IO.FileNotFoundException: Could not load file or assembly 'System.Data.SqlClient, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
```

Let me know if I have missed any info that you need.

**Comment by rowanmiller** [comment]
Hey,

We haven't been able to reproduce this based on the information here. Any chance you could share a project that we can run to see the issue?

~Rowan

**Comment by hahmed** [comment]
hey @rowanmiller 

Thanks for looking into this issue for me.

I have managed to reepro this at https://github.com/hahmed/TeamKudu

Once you have the app running, hit the database by entering a username and password, that should bring up the error - screenshot is attached.

<img width="1440" alt="screen shot 2015-11-11 at 20 36 29" src="https://cloud.githubusercontent.com/assets/658005/11102362/f27bb2ac-88b3-11e5-9e9e-60fa9e7b29fa.png">

**Comment by rowanmiller** [comment]
Ah, guess I should have asked what platform you were running on. SQL Client did not support .NET Core on non-Windows platforms in Beta 8. It will be supported in the upcoming RC1 release (albeit with a few bugs).

**Comment by hahmed** [comment]
Ok thanks... Once RC1 is shipped, I will re-open if I have any more issues.

**Comment by stevedesmond-ca** [comment]
I'm hitting this with rc1-final on Windows Server 2012 R2. App is being published from VS 2015 on a Windows 8.1 box (with the RC web tools), where it runs fine in both debug and release.

project.json has

    "dependencies": {
    "EntityFramework.Commands": "7.0.0-rc1-final",
    "EntityFramework.Core": "7.0.0-rc1-final",
    "EntityFramework.MicrosoftSqlServer": "7.0.0-rc1-final",
    ...
    "System.Data.SqlClient": "4.0.0-rc1-final"
    }
adding or removing `System.Data.SqlClient` doesn't seem to make a difference.

Is there anything that needs to be manually installed on the machine being published to? Again, it works fine from my 8.1 dev box, so it makes me think there's some sort of external dependency.

**Comment by gpeipman** [comment]
I have same problem on Azure websites. On local machine database connections work fine if I use CoreCLR x64.

**Comment by stevedesmond-ca** [comment]
Indeed, coreclr x64 -- my server does not appear to have .NET 4.6 installed, so that's where I'll check first later today

**Comment by hahmed** [comment]
@stevedesmond-ca I dont think "System.Data.SqlClient": "4.0.0-rc1-final" is even a thing? Looks like I am only getting back "System.Data.SqlClient": "4.0.0-beta-23516" from the feeds I am using.

This is still an issue for me...

**Comment by stevedesmond-ca** [comment]
yeah, I'm starting to think that's the problem too

**Comment by rowanmiller** [comment]
You are correct that the version number for SQL Client is `4.0.0-beta-23516` rather than `4.0.0-rc1-final` (SQL Client is built as part of the core .NET Framework... which uses a different versioning strategy than our team does). 

This error is a known issue with SQL Client (they are working on a fix). In the meantime, installing [Visual C++ Redistributable for Visual Studio 2012](https://www.microsoft.com/en-us/download/details.aspx?id=30679) may resolve the issue.

**Comment by stevedesmond-ca** [comment]
Already had that vcredist installed -- no dice.
I switched to dnx46 as a temporary workaround.

**Comment by divega** [comment]
@natemcmaster does this ring any bells?

**Comment by divega** [comment]
Could someone provide a stack trace for this on .NET Core RC1 on Windows (the previous stack traces in the thread may not actually be due to the same root cause I want to confirm it looks the same).

**Comment by divega** [comment]
cc @saurabh500

**Comment by gpeipman** [comment]
I have this on Azure: http://beerstore.azurewebsites.net It’s using .NET Core RC1. I can’t reproduce this problem on my Windows box.

 

Br,

Gunnar

**Comment by natemcmaster** [comment]
@divega @gpeipman if this doesn't reproduce on Windows locally, could it be one of the many [publish bug](https://github.com/search?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+user%3Aaspnet+publish&type=Issues&ref=searchresults)?

**Comment by rowanmiller** [comment]
cc @muratg who has more details about this issue. Apparently it's an issue with DNX that is known and is being worked on.

@muratg can you provide a DNX issue if there is one.

**Comment by muratg** [comment]
This is a `dnu publish` issue. There's a home repo bug that started the investigation this morning.

@anurse is investigating a fix, and he'll link a dnx bug here.

**Comment by hahmed** [comment]
@rowanmiller I tried running this again on mono rc1 final, looks like I am getting a new issue now.

![image](https://cloud.githubusercontent.com/assets/658005/11283845/8f53c6a0-8efe-11e5-9fc4-79f6db80c73a.png)

**Comment by divega** [comment]
That is a known limitation of the SqlClient implementation included in Mono. The one in .NET Core should work for this.

**Comment by hahmed** [comment]
@divega here comes my stack trace...

````
fail: Microsoft.Data.Entity.Query.Internal.QueryCompiler[1]
      An exception occurred in the database while iterating the results of a query.
      System.IO.FileNotFoundException: Could not load file or assembly 'System.Net.Security, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
      
      File name: 'System.Net.Security, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' ---> System.IO.FileNotFoundException: Could not load the specified file.
      File name: 'System.Net.Security'
         at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyName(AssemblyName assemblyName)
         at System.Runtime.Loader.AssemblyLoadContext.Resolve(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)
         at System.Data.SqlClient.SNI.SNITCPHandle..ctor(String serverName, Int32 port, Int64 timerExpire, Object callbackObject, Boolean parallel)
         at System.Data.SqlClient.SNI.SNIProxy.ConstructTcpHandle(String fullServerName, Int64 timerExpire, Object callbackObject, Boolean parallel)
         at System.Data.SqlClient.TdsParser.Connect(ServerInfo serverInfo, SqlInternalConnectionTds connHandler, Boolean ignoreSniOpenTimeout, Int64 timerExpire, Boolean encrypt, Boolean trustServerCert, Boolean integratedSecurity, Boolean withFailover)
         at System.Data.SqlClient.SqlInternalConnectionTds.AttemptOneLogin(ServerInfo serverInfo, Boolean ignoreSniOpenTimeout, TimeoutTimer timeout, Boolean withFailover)
         at System.Data.SqlClient.SqlInternalConnectionTds.LoginNoFailover(ServerInfo serverInfo, Boolean redirectedUserInstance, SqlConnectionString connectionOptions, TimeoutTimer timeout)
         at System.Data.SqlClient.SqlInternalConnectionTds.OpenLoginEnlist(TimeoutTimer timeout, SqlConnectionString connectionOptions, Boolean redirectedUserInstance)
         at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, Object providerInfo, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData)
         at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
         at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
         at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
         at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
         at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
         at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
         at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
         at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
         at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
         at System.Data.SqlClient.SqlConnection.Open()
         at Microsoft.Data.Entity.Storage.RelationalConnection.Open()
         at Microsoft.Data.Entity.Query.Internal.QueryingEnumerable.Enumerator.MoveNext()
         at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
         at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source)
         at lambda_method(Closure , QueryContext )
         at Microsoft.Data.Entity.Query.Internal.QueryCompiler.<>c__DisplayClass18_1`1.<CompileQuery>b__1(QueryContext qc)
fail: Microsoft.AspNet.Diagnostics.DeveloperExceptionPageMiddleware[0]
      An unhandled exception has occurred while executing the request
      System.IO.FileNotFoundException: Could not load the specified file.
      File name: 'EntityFramework.Core.resources'
         at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyName(AssemblyName assemblyName)
         at Microsoft.Data.Entity.Query.Internal.QueryCompiler.<>c__DisplayClass18_1`1.<CompileQuery>b__1(QueryContext qc)
         at System.Data.SqlClient.SNI.SNITCPHandle..ctor(String serverName, Int32 port, Int64 timerExpire, Object callbackObject, Boolean parallel)
         at System.Linq.Queryable.SingleOrDefault[TSource](IQueryable`1 source, Expression`1 predicate)
         at Team.Controllers.HomeController.<Login>d__13.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Microsoft.AspNet.Mvc.Controllers.ControllerActionExecutor.<CastToObject>d__8`1.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Microsoft.AspNet.Mvc.Controllers.ControllerActionInvoker.<InvokeActionAsync>d__6.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Microsoft.AspNet.Mvc.Controllers.FilterActionInvoker.<InvokeActionFilterAsync>d__53.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at Microsoft.AspNet.Mvc.Controllers.FilterActionInvoker.<InvokeAsync>d__44.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Microsoft.AspNet.Mvc.Infrastructure.MvcRouteHandler.<RouteAsync>d__6.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at Microsoft.AspNet.Mvc.Routing.InnerAttributeRoute.<RouteAsync>d__10.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at Microsoft.AspNet.Routing.RouteCollection.<RouteAsync>d__9.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Microsoft.AspNet.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Microsoft.AspNet.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at Microsoft.AspNet.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Microsoft.AspNet.Diagnostics.Entity.MigrationsEndPointMiddleware.<Invoke>d__5.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Microsoft.AspNet.Diagnostics.Entity.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at Microsoft.AspNet.Diagnostics.Entity.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Microsoft.AspNet.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
info: Microsoft.AspNet.Hosting.Internal.HostingEngine[2]
      Request finished in 0.1084ms 500 text/html; charset=utf-8
````

**Comment by natemcmaster** [comment]
@hahmed this is a bug in `dnu restore`. Add `"Microsoft.NETCore.Platforms": "1.0.1-*"` to your dependencies. See https://github.com/aspnet/EntityFramework/pull/3689#issuecomment-158201904.

**Comment by hahmed** [comment]
@natemcmaster Is that the only package I need to add? Looks like I am getting a whole bunch of weird(er) issues...

````
Haroons-MacBook-Pro:teamkudu haroon$ dnu build --quiet
Microsoft .NET Development Utility CoreClr-x64-1.0.0-rc1-16202


Building TeamKudu for DNX,Version=v4.5.1
/Users/haroon/Projects/TeamKudu/project.json(0,0): error NU1001: The dependency fx/mscorlib  could not be resolved.
/Users/haroon/Projects/TeamKudu/project.json(0,0): error NU1001: The dependency fx/System  could not be resolved.
/Users/haroon/Projects/TeamKudu/project.json(0,0): error NU1001: The dependency fx/System.Core  could not be resolved.
/Users/haroon/Projects/TeamKudu/project.json(0,0): error NU1001: The dependency fx/Microsoft.CSharp  could not be resolved.
/Users/haroon/Projects/TeamKudu/project.json(0,0): error NU1001: The dependency fx/System.Collections  could not be resolved.
/Users/haroon/Projects/TeamKudu/project.json(0,0): error NU1001: The dependency fx/System.ComponentModel.DataAnnotations  could not be resolved.
/Users/haroon/Projects/TeamKudu/project.json(0,0): error NU1001: The dependency fx/System.Diagnostics.Debug  could not be resolved.
/Users/haroon/Projects/TeamKudu/project.json(0,0): error NU1001: The dependency fx/System.Diagnostics.Tools  could not be resolved.
/Users/haroon/Projects/TeamKudu/project.json(0,0): error NU1001: The dependency fx/System.Globalization  could not be resolved.
/Users/haroon/Projects/TeamKudu/project.json(0,0): error NU1001: The dependency fx/System.Linq  could not be resolved.
/Users/haroon/Projects/TeamKudu/project.json(0,0): error NU1001: The dependency fx/System.Linq.Expressions  could not be resolved.
/Users/haroon/Projects/TeamKudu/project.json(0,0): error NU1001: The dependency fx/System.Linq.Queryable  could not be resolved.
/Users/haroon/Projects/TeamKudu/project.json(0,0): error NU1001: The dependency fx/System.ObjectModel  could not be resolved.
/Users/haroon/Projects/TeamKudu/project.json(0,0): error NU1001: The dependency fx/System.Reflection  could not be resolved.
/Users/haroon/Projects/TeamKudu/project.json(0,0): error NU1001: The dependency fx/System.Reflection.Extensions  could not be resolved.
/Users/haroon/Projects/TeamKudu/project.json(0,0): error NU1001: The dependency fx/System.Resources.ResourceManager  could not be resolved.
/Users/haroon/Projects/TeamKudu/project.json(0,0): error NU1001: The dependency fx/System.Runtime  could not be resolved.
/Users/haroon/Projects/TeamKudu/project.json(0,0): error NU1001: The dependency fx/System.Runtime.Extensions  could not be resolved.
/Users/haroon/Projects/TeamKudu/project.json(0,0): error NU1001: The dependency fx/System.Threading  could not be resolved.
/Users/haroon/Projects/TeamKudu/project.json(0,0): error NU1001: The dependency fx/System.Data  could not be resolved.
/Users/haroon/Projects/TeamKudu/project.json(0,0): error NU1001: The dependency fx/System.Transactions  could not be resolved.
/Users/haroon/Projects/TeamKudu/project.json(0,0): error NU1001: The dependency fx/System.IO  could not be resolved.
/Users/haroon/Projects/TeamKudu/project.json(0,0): error NU1001: The dependency fx/System.Text.Encoding  could not be resolved.
/Users/haroon/Projects/TeamKudu/project.json(0,0): error NU1001: The dependency fx/System.Threading.Tasks  could not be resolved.
/Users/haroon/Projects/TeamKudu/project.json(0,0): error NU1001: The dependency fx/System.Net.Http  could not be resolved.
/Users/haroon/Projects/TeamKudu/project.json(0,0): error NU1001: The dependency fx/System.Security  could not be resolved.
/Users/haroon/Projects/TeamKudu/project.json(0,0): error NU1001: The dependency fx/System.Xml  could not be resolved.
/Users/haroon/Projects/TeamKudu/project.json(0,0): error NU1001: The dependency fx/System.Xml.Linq  could not be resolved.
/Users/haroon/Projects/TeamKudu/project.json(0,0): error NU1001: The dependency fx/System.Configuration  could not be resolved.
/Users/haroon/Projects/TeamKudu/project.json(0,0): error NU1001: The dependency fx/System.Collections.Concurrent  could not be resolved.
````
It goes on for a while... do you want all of it? Or is this something you have seen?

**Comment by natemcmaster** [comment]
@hahmed This is a related lower-level issues in Linux, CoreCLR, and SqlClient. You can open bugs against SQL Client in the https://github.com/dotnet/corefx/ repo. (Your error message is identical to https://github.com/dotnet/corefx/issues/4339)

**Comment by rowanmiller** [comment]
Closing out this issue as it was confirmed to be a DNX/DNU issue and they are currently working on a fix.

**Comment by Purgator** [comment]
Hello, i got this error too on rc1-final.
I try to launch dnx on Linux, and the database is on a windows server.

What to do please ? Is there any chance that i get my website working ?


FileNotFoundException: Could not load file or assembly 'System.Net.Security, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

**Comment by rowanmiller** [comment]
@Purgator that looks like the issue tracked by https://github.com/dotnet/corefx/issues/4230 (and also discussed in https://github.com/dotnet/corefx/issues/4217). Looks like adding an explicit reference to `System.Net,Security` in your project.json should resolve the issue.

```
"System.Net.Security": "4.0.0-beta-23405"
```

**Comment by Purgator** [comment]
@rowanmiller Thank you it solved the issue.
Now i got this exeption : DllNotFoundException: Unable to load DLL 'api-ms-win-core-localization-obsolete-l1-2-0.dll': The specified module could not be found.
I found that topic that explain how to fix it : https://github.com/dotnet/corefx/issues/4579
It say it's suppose to be fixed, but not for me (rc1-final).

**Comment by rowanmiller** [comment]
@Purgator that issue is in the RC2 milestone... so you should expect the fix to come in the next pre-release (it was fixed after RC1 shipped).

**Comment by raffaeler** [comment]
I still have this:
       System.IO.FileNotFoundException: Could not load file or assembly 'System.Net.Security, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

environment: docker
DNX SDK: 1.0.0-rc2
.NET Core x64

Any workarounds?

**Comment by natemcmaster** [comment]
@raffaeler this was a known issue with RC1 and DNX (see https://github.com/aspnet/EntityFramework/pull/3689#issuecomment-158201904). FYI we are retiring dnx in RC2 and switching to dotnet-cli. Dotnet-cli should not have this issue. See https://github.com/aspnet/dnx#dnx-retired.

**Comment by raffaeler** [comment]
Thanks but I need asp.net core and afaik I still can't use dotnet cli with it.
I hoped in a dirty solution to make my tests, just that.

**Comment by xferra** [comment]
Environment: 1.0.0-rc1-final, coreclr
Works as expected on Windows 8 x64 but with exceptions on ubuntu.14.04-x64.
Exception occurs only in runtime when I try to get some data from db (mssql).

project.json:
```
...
    "dependencies": {
        "EntityFramework.Commands": "7.0.0-rc1-final",
        "EntityFramework.MicrosoftSqlServer": "7.0.0-rc1-final",
        "EntityFramework.MicrosoftSqlServer.Design": "7.0.0-rc1-final",
        ...
        "System.Data.SqlClient": "4.0.0-rc1-final"
    },
    "commands": {
        "web": "Microsoft.AspNet.Server.Kestrel --server.urls=http://*:60708/"
    },
    "frameworks": {
        "dnxcore50": { }
    }
...
```

Exception:
```
fail: Microsoft.AspNet.Diagnostics.ExceptionHandlerMiddleware[0]
      An unhandled exception has occurred: Could not load file or assembly 'System.Data.SqlClient, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

      System.IO.FileNotFoundException: Could not load file or assembly 'System.Data.SqlClient, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
      
      File name: 'System.Data.SqlClient, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' ---> System.IO.FileNotFoundException: Could not load the specified file.
      File name: 'System.Data.SqlClient'
         at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyName(AssemblyName assemblyName)
         at System.Runtime.Loader.AssemblyLoadContext.Resolve(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)
         at Metrics.Api.Attributes.Filters.ExceptionFilterAttribute.OnException(ExceptionContext context)
         at Microsoft.AspNet.Mvc.Controllers.FilterActionInvoker.<InvokeExceptionFilterAsync>d__51.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Microsoft.AspNet.Mvc.Controllers.FilterActionInvoker.<InvokeResourceFilterAsync>d__49.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at Microsoft.AspNet.Mvc.Controllers.FilterActionInvoker.<InvokeAsync>d__44.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Microsoft.AspNet.Mvc.Infrastructure.MvcRouteHandler.<RouteAsync>d__6.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at Microsoft.AspNet.Mvc.Routing.InnerAttributeRoute.<RouteAsync>d__10.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at Microsoft.AspNet.Routing.RouteCollection.<RouteAsync>d__9.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Microsoft.AspNet.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at IdentityModel.AspNet.ScopeValidation.ScopeValidationMiddleware.<Invoke>d__3.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Microsoft.AspNet.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at Microsoft.AspNet.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at IdentityServer4.AccessTokenValidation.IdentityServerAuthenticationMiddleware.<Invoke>d__7.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Microsoft.AspNet.IISPlatformHandler.IISPlatformHandlerMiddleware.<Invoke>d__8.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Microsoft.AspNet.Diagnostics.ExceptionHandlerMiddleware.<Invoke>d__6.MoveNext()`

**Comment by raptaml** [comment]
Same here on Ubuntu 14.04 with DNX/DNU tool chain for ASP.NET MVC 6 on .NET Core . Cannot call method which references System.Data.SqlClient. Getting same StackTrace as OP.
