### ISSUE TITLE
.OrderByDescending(pm => pm.MainItem == true) generates flawed SQL

### ISSUE THREAD

**Issue by jancg** [dotnet/efcore#4519]
HAS BEEN SOLVED IN 1.0.0 (or perhaps earlier)

pm.MainItem is a nullable bit in the database

EF6 could handle this nicely. See also http://stackoverflow.com/questions/35292726/is-ef7-anywhere-near-usable.

**Comment by ErikEJ** [comment]
That bug has been fixed in the latest codebase, and the fix will be available in RC2

**Comment by jancg** [comment]
'not planned'? Why? We always intent to fix bugs in our code. I guess I should stick to EF6 forever? EF Core is still not up to par compared to EF6 when it comes down to query generation.

**Comment by ajcvickers** [comment]
@jancg This is a really old issues that was closed 6 years ago. All that is happening here is that the GitHub closed-reason is changing. If you think there is still a bug here, then please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.
