### ISSUE TITLE
Insert-Update Entity with Computed column in sql

### ISSUE THREAD

**Issue by ampalla** [dotnet/efcore#5282]
When inserting or updating  an entity with computed column in sql, I get the error:

> Column 'inserted.Status' cannot be referenced in the OUTPUT clause because the column definition contains a subquery or references a function that performs user or system data access. A function is assumed by default to perform data access if it is not schemabound. Consider removing the subquery or function from the column definition or removing the column from the OUTPUT clause

Computed columns should not be included in insert or update statements.

**Comment by rowanmiller** [comment]
Are you using RC1? Probably already fixed in https://github.com/aspnet/EntityFramework/issues/1441

**Comment by ampalla** [comment]
I am using RC1 and I have set MaxBatchSize to 1.

**Comment by rowanmiller** [comment]
This is fixed in RC2, which will ship shortly.

**Comment by xrkolovos** [comment]
I am having the same issue in rc2.
in my model i have registered the property like this
```
[DatabaseGenerated(DatabaseGeneratedOption.Computed)]
public SubjectStatus? SubjectStatus { get; set; }
```
Insert statement is running fine.
But on update i have this issue because my computed column uses a Scalar-valued Function.
the sql statement that is created on update is the following.
```
UPDATE [Subjects] SET [CouncilId] = @p1, ... [SubjectGroupId] = @p14
OUTPUT INSERTED.[SubjectStatus]
INTO @inserted0
WHERE [Id] = @p0;
SELECT [SubjectStatus] FROM @inserted0;
```

**Comment by ampalla** [comment]
I tested it a few minutes ago and the problem isn't solved for update statements

**Comment by rowanmiller** [comment]
@xrkolovos @ampalla can you open a new issue, the specific scenario covered by this issue is fixed.
